# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analysiswindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AnalysisWindow(object):
    def setupUi(self, AnalysisWindow):
        AnalysisWindow.setObjectName("AnalysisWindow")
        AnalysisWindow.setEnabled(True)
        AnalysisWindow.resize(1080, 800)
        AnalysisWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(AnalysisWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainMenu = QtWidgets.QWidget(self.centralwidget)
        self.mainMenu.setEnabled(True)
        self.mainMenu.setAutoFillBackground(False)
        self.mainMenu.setStyleSheet("")
        self.mainMenu.setObjectName("mainMenu")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.mainMenu)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnMainMenu = QtWidgets.QPushButton(self.mainMenu)
        self.btnMainMenu.setText("")
        self.btnMainMenu.setObjectName("btnMainMenu")
        self.horizontalLayout_5.addWidget(self.btnMainMenu)
        self.label = QtWidgets.QLabel(self.mainMenu)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.btnDevices = QtWidgets.QPushButton(self.mainMenu)
        self.btnDevices.setMinimumSize(QtCore.QSize(32, 32))
        self.btnDevices.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDevices.setStyleSheet("")
        self.btnDevices.setText("")
        self.btnDevices.setIconSize(QtCore.QSize(32, 32))
        self.btnDevices.setObjectName("btnDevices")
        self.horizontalLayout_5.addWidget(self.btnDevices)
        self.verticalLayout.addWidget(self.mainMenu)
        self.anaysisParam = QtWidgets.QWidget(self.centralwidget)
        self.anaysisParam.setStyleSheet("border-bottom:1px solid #E2E2E2;\n"
"margin-left:0.5em;\n"
"margin-right:0.5em;")
        self.anaysisParam.setObjectName("anaysisParam")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.anaysisParam)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.vehicleTitle = QtWidgets.QLabel(self.anaysisParam)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.vehicleTitle.setFont(font)
        self.vehicleTitle.setObjectName("vehicleTitle")
        self.horizontalLayout_4.addWidget(self.vehicleTitle)
        self.editVehicle = QtWidgets.QPushButton(self.anaysisParam)
        self.editVehicle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editVehicle.setObjectName("editVehicle")
        self.horizontalLayout_4.addWidget(self.editVehicle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.anaysisParam)
        self.actionMenu = QtWidgets.QWidget(self.centralwidget)
        self.actionMenu.setObjectName("actionMenu")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.actionMenu)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnBusCan = QtWidgets.QPushButton(self.actionMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBusCan.sizePolicy().hasHeightForWidth())
        self.btnBusCan.setSizePolicy(sizePolicy)
        self.btnBusCan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/icons16/application-terminal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBusCan.setIcon(icon)
        self.btnBusCan.setObjectName("btnBusCan")
        self.horizontalLayout_2.addWidget(self.btnBusCan)
        self.btnBusLin = QtWidgets.QPushButton(self.actionMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBusLin.sizePolicy().hasHeightForWidth())
        self.btnBusLin.setSizePolicy(sizePolicy)
        self.btnBusLin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBusLin.setObjectName("btnBusLin")
        self.horizontalLayout_2.addWidget(self.btnBusLin)
        self.btnBusKln = QtWidgets.QPushButton(self.actionMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBusKln.sizePolicy().hasHeightForWidth())
        self.btnBusKln.setSizePolicy(sizePolicy)
        self.btnBusKln.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBusKln.setObjectName("btnBusKln")
        self.horizontalLayout_2.addWidget(self.btnBusKln)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btnShowRightMenu = QtWidgets.QPushButton(self.actionMenu)
        self.btnShowRightMenu.setObjectName("btnShowRightMenu")
        self.horizontalLayout_2.addWidget(self.btnShowRightMenu)
        self.verticalLayout.addWidget(self.actionMenu)
        self.body = QtWidgets.QWidget(self.centralwidget)
        self.body.setObjectName("body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.body)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.msgTable = QtWidgets.QTableView(self.body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgTable.sizePolicy().hasHeightForWidth())
        self.msgTable.setSizePolicy(sizePolicy)
        self.msgTable.setMinimumSize(QtCore.QSize(760, 0))
        self.msgTable.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.msgTable.setAlternatingRowColors(True)
        self.msgTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.msgTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.msgTable.setSortingEnabled(True)
        self.msgTable.setCornerButtonEnabled(True)
        self.msgTable.setObjectName("msgTable")
        self.horizontalLayout.addWidget(self.msgTable)
        self.rightMenu = QtWidgets.QWidget(self.body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightMenu.sizePolicy().hasHeightForWidth())
        self.rightMenu.setSizePolicy(sizePolicy)
        self.rightMenu.setMinimumSize(QtCore.QSize(100, 0))
        self.rightMenu.setMaximumSize(QtCore.QSize(16777215, 1920))
        self.rightMenu.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.rightMenu.setStyleSheet("")
        self.rightMenu.setObjectName("rightMenu")
        self.rightMenuLayout = QtWidgets.QVBoxLayout(self.rightMenu)
        self.rightMenuLayout.setContentsMargins(-1, 0, -1, -1)
        self.rightMenuLayout.setObjectName("rightMenuLayout")
        self.cardDisplay = QtWidgets.QWidget(self.rightMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardDisplay.sizePolicy().hasHeightForWidth())
        self.cardDisplay.setSizePolicy(sizePolicy)
        self.cardDisplay.setObjectName("cardDisplay")
        self.cardDisplayLayout = QtWidgets.QVBoxLayout(self.cardDisplay)
        self.cardDisplayLayout.setContentsMargins(-1, 0, -1, -1)
        self.cardDisplayLayout.setSpacing(0)
        self.cardDisplayLayout.setObjectName("cardDisplayLayout")
        self.cardHeaderDisplay = QtWidgets.QWidget(self.cardDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardHeaderDisplay.sizePolicy().hasHeightForWidth())
        self.cardHeaderDisplay.setSizePolicy(sizePolicy)
        self.cardHeaderDisplay.setStyleSheet("")
        self.cardHeaderDisplay.setObjectName("cardHeaderDisplay")
        self.cardDisplayHLayout = QtWidgets.QHBoxLayout(self.cardHeaderDisplay)
        self.cardDisplayHLayout.setObjectName("cardDisplayHLayout")
        self.cardDisplayTitle = QtWidgets.QLabel(self.cardHeaderDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardDisplayTitle.sizePolicy().hasHeightForWidth())
        self.cardDisplayTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cardDisplayTitle.setFont(font)
        self.cardDisplayTitle.setStyleSheet("background:none;\n"
"border:0;\n"
"border-radius:0;")
        self.cardDisplayTitle.setObjectName("cardDisplayTitle")
        self.cardDisplayHLayout.addWidget(self.cardDisplayTitle)
        self.btnCollapseDisplay = QtWidgets.QPushButton(self.cardHeaderDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCollapseDisplay.sizePolicy().hasHeightForWidth())
        self.btnCollapseDisplay.setSizePolicy(sizePolicy)
        self.btnCollapseDisplay.setText("")
        self.btnCollapseDisplay.setObjectName("btnCollapseDisplay")
        self.cardDisplayHLayout.addWidget(self.btnCollapseDisplay)
        self.cardDisplayLayout.addWidget(self.cardHeaderDisplay)
        self.cardBodyDisplay = QtWidgets.QWidget(self.cardDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardBodyDisplay.sizePolicy().hasHeightForWidth())
        self.cardBodyDisplay.setSizePolicy(sizePolicy)
        self.cardBodyDisplay.setStyleSheet("")
        self.cardBodyDisplay.setObjectName("cardBodyDisplay")
        self.formDisplayLayout = QtWidgets.QFormLayout(self.cardBodyDisplay)
        self.formDisplayLayout.setVerticalSpacing(6)
        self.formDisplayLayout.setObjectName("formDisplayLayout")
        self.label_40 = QtWidgets.QLabel(self.cardBodyDisplay)
        self.label_40.setObjectName("label_40")
        self.formDisplayLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.checkMaskStatic = QtWidgets.QCheckBox(self.cardBodyDisplay)
        self.checkMaskStatic.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkMaskStatic.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkMaskStatic.setText("")
        self.checkMaskStatic.setObjectName("checkMaskStatic")
        self.formDisplayLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkMaskStatic)
        self.label_30 = QtWidgets.QLabel(self.cardBodyDisplay)
        self.label_30.setObjectName("label_30")
        self.formDisplayLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.label_20 = QtWidgets.QLabel(self.cardBodyDisplay)
        self.label_20.setObjectName("label_20")
        self.formDisplayLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.checkOverwrite = QtWidgets.QCheckBox(self.cardBodyDisplay)
        self.checkOverwrite.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkOverwrite.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkOverwrite.setText("")
        self.checkOverwrite.setObjectName("checkOverwrite")
        self.formDisplayLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.checkOverwrite)
        self.keepDurationLayout = QtWidgets.QWidget(self.cardBodyDisplay)
        self.keepDurationLayout.setObjectName("keepDurationLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.keepDurationLayout)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.comboKeepDuration = QtWidgets.QComboBox(self.keepDurationLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboKeepDuration.sizePolicy().hasHeightForWidth())
        self.comboKeepDuration.setSizePolicy(sizePolicy)
        self.comboKeepDuration.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboKeepDuration.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.comboKeepDuration.setStyleSheet("text-align:right")
        self.comboKeepDuration.setObjectName("comboKeepDuration")
        self.horizontalLayout_7.addWidget(self.comboKeepDuration)
        self.formDisplayLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.keepDurationLayout)
        self.cardDisplayLayout.addWidget(self.cardBodyDisplay)
        self.rightMenuLayout.addWidget(self.cardDisplay)
        self.cardFilter = QtWidgets.QWidget(self.rightMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardFilter.sizePolicy().hasHeightForWidth())
        self.cardFilter.setSizePolicy(sizePolicy)
        self.cardFilter.setObjectName("cardFilter")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cardFilter)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cardHeaderFilter = QtWidgets.QWidget(self.cardFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardHeaderFilter.sizePolicy().hasHeightForWidth())
        self.cardHeaderFilter.setSizePolicy(sizePolicy)
        self.cardHeaderFilter.setStyleSheet("")
        self.cardHeaderFilter.setObjectName("cardHeaderFilter")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.cardHeaderFilter)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cardFilterTitle = QtWidgets.QLabel(self.cardHeaderFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardFilterTitle.sizePolicy().hasHeightForWidth())
        self.cardFilterTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cardFilterTitle.setFont(font)
        self.cardFilterTitle.setStyleSheet("background:none;\n"
"border:0;\n"
"border-radius:0;")
        self.cardFilterTitle.setObjectName("cardFilterTitle")
        self.horizontalLayout_6.addWidget(self.cardFilterTitle)
        self.btnCollapseFilter = QtWidgets.QPushButton(self.cardHeaderFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCollapseFilter.sizePolicy().hasHeightForWidth())
        self.btnCollapseFilter.setSizePolicy(sizePolicy)
        self.btnCollapseFilter.setText("")
        self.btnCollapseFilter.setObjectName("btnCollapseFilter")
        self.horizontalLayout_6.addWidget(self.btnCollapseFilter)
        self.verticalLayout_2.addWidget(self.cardHeaderFilter)
        self.cardBodyFilter = QtWidgets.QWidget(self.cardFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardBodyFilter.sizePolicy().hasHeightForWidth())
        self.cardBodyFilter.setSizePolicy(sizePolicy)
        self.cardBodyFilter.setStyleSheet("")
        self.cardBodyFilter.setObjectName("cardBodyFilter")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cardBodyFilter)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.idFilter = QtWidgets.QTreeWidget(self.cardBodyFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idFilter.sizePolicy().hasHeightForWidth())
        self.idFilter.setSizePolicy(sizePolicy)
        self.idFilter.setColumnCount(1)
        self.idFilter.setObjectName("idFilter")
        self.verticalLayout_3.addWidget(self.idFilter)
        self.verticalLayout_2.addWidget(self.cardBodyFilter)
        self.rightMenuLayout.addWidget(self.cardFilter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.rightMenuLayout.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.rightMenu)
        self.verticalLayout.addWidget(self.body)
        self.chatMenu = QtWidgets.QWidget(self.centralwidget)
        self.chatMenu.setObjectName("chatMenu")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.chatMenu)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.chatMenu)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.chatMenu)
        AnalysisWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AnalysisWindow)
        self.statusbar.setObjectName("statusbar")
        AnalysisWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AnalysisWindow)
        QtCore.QMetaObject.connectSlotsByName(AnalysisWindow)

    def retranslateUi(self, AnalysisWindow):
        _translate = QtCore.QCoreApplication.translate
        AnalysisWindow.setWindowTitle(_translate("AnalysisWindow", "Share-CAN"))
        self.mainMenu.setProperty("cssClass", _translate("AnalysisWindow", "mainMenu"))
        self.label.setText(_translate("AnalysisWindow", "APP_NAME"))
        self.label.setProperty("cssClass", _translate("AnalysisWindow", "appTitle"))
        self.btnDevices.setProperty("cssClass", _translate("AnalysisWindow", "menuBtn"))
        self.vehicleTitle.setText(_translate("AnalysisWindow", "Ford Focus - <b>2017</b> - WWFG1345FEM"))
        self.editVehicle.setText(_translate("AnalysisWindow", "Edit"))
        self.btnBusCan.setText(_translate("AnalysisWindow", "CAN_BTN"))
        self.btnBusLin.setText(_translate("AnalysisWindow", "LIN_BTN"))
        self.btnBusKln.setText(_translate("AnalysisWindow", "KLN_BTN"))
        self.btnShowRightMenu.setText(_translate("AnalysisWindow", "HIDE_MENU"))
        self.cardDisplay.setProperty("cssClass", _translate("AnalysisWindow", "card"))
        self.cardHeaderDisplay.setProperty("cssClass", _translate("AnalysisWindow", "cardHeader"))
        self.cardDisplayTitle.setText(_translate("AnalysisWindow", "DISPLAY"))
        self.cardDisplayTitle.setProperty("cssClass", _translate("AnalysisWindow", "cardTitle"))
        self.cardBodyDisplay.setProperty("cssClass", _translate("AnalysisWindow", "cardBody"))
        self.label_40.setText(_translate("AnalysisWindow", "MASK_STATIC"))
        self.label_30.setText(_translate("AnalysisWindow", "KEEP_DURATION"))
        self.label_20.setText(_translate("AnalysisWindow", "GROUP_ID"))
        self.cardFilter.setProperty("cssClass", _translate("AnalysisWindow", "card"))
        self.cardHeaderFilter.setProperty("cssClass", _translate("AnalysisWindow", "cardHeader"))
        self.cardFilterTitle.setText(_translate("AnalysisWindow", "FILTERS"))
        self.cardFilterTitle.setProperty("cssClass", _translate("AnalysisWindow", "cardTitle"))
        self.cardBodyFilter.setProperty("cssClass", _translate("AnalysisWindow", "cardBody"))
        self.idFilter.setSortingEnabled(True)
        self.idFilter.headerItem().setText(0, _translate("AnalysisWindow", "BUS - ID"))
        self.label_2.setText(_translate("AnalysisWindow", "BOTTOM WIDGET  : Show active functions and unread chat messages"))

