# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form-bus.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BUS(object):
    def setupUi(self, BUS):
        BUS.setObjectName("BUS")
        BUS.resize(993, 428)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BUS.sizePolicy().hasHeightForWidth())
        BUS.setSizePolicy(sizePolicy)
        BUS.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(BUS)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(BUS)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setObjectName("tabWidget")
        self.tabIface = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabIface.sizePolicy().hasHeightForWidth())
        self.tabIface.setSizePolicy(sizePolicy)
        self.tabIface.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabIface.setStyleSheet("")
        self.tabIface.setObjectName("tabIface")
        self.tabIfaceLayout = QtWidgets.QVBoxLayout(self.tabIface)
        self.tabIfaceLayout.setObjectName("tabIfaceLayout")
        self.gridIface = QtWidgets.QWidget(self.tabIface)
        self.gridIface.setObjectName("gridIface")
        self.ifaceGridLayout = QtWidgets.QGridLayout(self.gridIface)
        self.ifaceGridLayout.setObjectName("ifaceGridLayout")
        self.busTitleSpeed = QtWidgets.QLabel(self.gridIface)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.busTitleSpeed.setFont(font)
        self.busTitleSpeed.setObjectName("busTitleSpeed")
        self.ifaceGridLayout.addWidget(self.busTitleSpeed, 0, 3, 1, 1)
        self.busTitleIface = QtWidgets.QLabel(self.gridIface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.busTitleIface.sizePolicy().hasHeightForWidth())
        self.busTitleIface.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.busTitleIface.setFont(font)
        self.busTitleIface.setObjectName("busTitleIface")
        self.ifaceGridLayout.addWidget(self.busTitleIface, 0, 0, 1, 1)
        self.busTitlePreset = QtWidgets.QLabel(self.gridIface)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.busTitlePreset.setFont(font)
        self.busTitlePreset.setObjectName("busTitlePreset")
        self.ifaceGridLayout.addWidget(self.busTitlePreset, 0, 1, 1, 1)
        self.busTitleName = QtWidgets.QLabel(self.gridIface)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.busTitleName.setFont(font)
        self.busTitleName.setObjectName("busTitleName")
        self.ifaceGridLayout.addWidget(self.busTitleName, 0, 2, 1, 1)
        self.busTitleGw = QtWidgets.QLabel(self.gridIface)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.busTitleGw.setFont(font)
        self.busTitleGw.setObjectName("busTitleGw")
        self.ifaceGridLayout.addWidget(self.busTitleGw, 0, 4, 1, 1)
        self.busTitleActive = QtWidgets.QLabel(self.gridIface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.busTitleActive.sizePolicy().hasHeightForWidth())
        self.busTitleActive.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.busTitleActive.setFont(font)
        self.busTitleActive.setObjectName("busTitleActive")
        self.ifaceGridLayout.addWidget(self.busTitleActive, 0, 5, 1, 1)
        self.tabIfaceLayout.addWidget(self.gridIface)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.tabIfaceLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tabIface, "")
        self.tabBus = QtWidgets.QWidget()
        self.tabBus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabBus.setObjectName("tabBus")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabBus)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.busEditor = QtWidgets.QWidget(self.tabBus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.busEditor.sizePolicy().hasHeightForWidth())
        self.busEditor.setSizePolicy(sizePolicy)
        self.busEditor.setObjectName("busEditor")
        self.gridLayout = QtWidgets.QGridLayout(self.busEditor)
        self.gridLayout.setObjectName("gridLayout")
        self.labelWire1 = QtWidgets.QLabel(self.busEditor)
        self.labelWire1.setObjectName("labelWire1")
        self.gridLayout.addWidget(self.labelWire1, 7, 0, 1, 1)
        self.labelKlnInit = QtWidgets.QLabel(self.busEditor)
        self.labelKlnInit.setObjectName("labelKlnInit")
        self.gridLayout.addWidget(self.labelKlnInit, 4, 0, 1, 1)
        self.editorSave = QtWidgets.QPushButton(self.busEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editorSave.sizePolicy().hasHeightForWidth())
        self.editorSave.setSizePolicy(sizePolicy)
        self.editorSave.setMinimumSize(QtCore.QSize(180, 0))
        self.editorSave.setObjectName("editorSave")
        self.gridLayout.addWidget(self.editorSave, 13, 4, 1, 1)
        self.fldOBD1 = QtWidgets.QComboBox(self.busEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldOBD1.sizePolicy().hasHeightForWidth())
        self.fldOBD1.setSizePolicy(sizePolicy)
        self.fldOBD1.setMinimumSize(QtCore.QSize(80, 0))
        self.fldOBD1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fldOBD1.setObjectName("fldOBD1")
        self.gridLayout.addWidget(self.fldOBD1, 9, 1, 1, 1)
        self.fldLinVersion = QtWidgets.QComboBox(self.busEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldLinVersion.sizePolicy().hasHeightForWidth())
        self.fldLinVersion.setSizePolicy(sizePolicy)
        self.fldLinVersion.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fldLinVersion.setObjectName("fldLinVersion")
        self.gridLayout.addWidget(self.fldLinVersion, 3, 1, 1, 1)
        self.labelPreset = QtWidgets.QLabel(self.busEditor)
        self.labelPreset.setObjectName("labelPreset")
        self.gridLayout.addWidget(self.labelPreset, 0, 0, 1, 1)
        self.fldWire21 = QtWidgets.QComboBox(self.busEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldWire21.sizePolicy().hasHeightForWidth())
        self.fldWire21.setSizePolicy(sizePolicy)
        self.fldWire21.setMinimumSize(QtCore.QSize(80, 0))
        self.fldWire21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fldWire21.setObjectName("fldWire21")
        self.gridLayout.addWidget(self.fldWire21, 7, 5, 1, 1)
        self.labelOBD1 = QtWidgets.QLabel(self.busEditor)
        self.labelOBD1.setObjectName("labelOBD1")
        self.gridLayout.addWidget(self.labelOBD1, 9, 0, 1, 1)
        self.fldWire10 = QtWidgets.QComboBox(self.busEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldWire10.sizePolicy().hasHeightForWidth())
        self.fldWire10.setSizePolicy(sizePolicy)
        self.fldWire10.setMinimumSize(QtCore.QSize(80, 0))
        self.fldWire10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fldWire10.setObjectName("fldWire10")
        self.gridLayout.addWidget(self.fldWire10, 7, 1, 1, 1)
        self.labelName = QtWidgets.QLabel(self.busEditor)
        self.labelName.setObjectName("labelName")
        self.gridLayout.addWidget(self.labelName, 1, 0, 1, 1)
        self.labelLinVersion = QtWidgets.QLabel(self.busEditor)
        self.labelLinVersion.setObjectName("labelLinVersion")
        self.gridLayout.addWidget(self.labelLinVersion, 3, 0, 1, 1)
        self.fldOBD2 = QtWidgets.QComboBox(self.busEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldOBD2.sizePolicy().hasHeightForWidth())
        self.fldOBD2.setSizePolicy(sizePolicy)
        self.fldOBD2.setMinimumSize(QtCore.QSize(80, 0))
        self.fldOBD2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fldOBD2.setObjectName("fldOBD2")
        self.gridLayout.addWidget(self.fldOBD2, 9, 4, 1, 1)
        self.fldWire11 = QtWidgets.QComboBox(self.busEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldWire11.sizePolicy().hasHeightForWidth())
        self.fldWire11.setSizePolicy(sizePolicy)
        self.fldWire11.setMinimumSize(QtCore.QSize(80, 0))
        self.fldWire11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fldWire11.setObjectName("fldWire11")
        self.gridLayout.addWidget(self.fldWire11, 7, 2, 1, 1)
        self.fldPreset = QtWidgets.QComboBox(self.busEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldPreset.sizePolicy().hasHeightForWidth())
        self.fldPreset.setSizePolicy(sizePolicy)
        self.fldPreset.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fldPreset.setObjectName("fldPreset")
        self.gridLayout.addWidget(self.fldPreset, 0, 1, 1, 5)
        self.fldWire20 = QtWidgets.QComboBox(self.busEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldWire20.sizePolicy().hasHeightForWidth())
        self.fldWire20.setSizePolicy(sizePolicy)
        self.fldWire20.setMinimumSize(QtCore.QSize(80, 0))
        self.fldWire20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fldWire20.setObjectName("fldWire20")
        self.gridLayout.addWidget(self.fldWire20, 7, 4, 1, 1)
        self.busEditorBtn = QtWidgets.QWidget(self.busEditor)
        self.busEditorBtn.setObjectName("busEditorBtn")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.busEditorBtn)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout.addWidget(self.busEditorBtn, 13, 0, 1, 2)
        self.fldKlnInit = QtWidgets.QComboBox(self.busEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldKlnInit.sizePolicy().hasHeightForWidth())
        self.fldKlnInit.setSizePolicy(sizePolicy)
        self.fldKlnInit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fldKlnInit.setObjectName("fldKlnInit")
        self.gridLayout.addWidget(self.fldKlnInit, 4, 1, 1, 1)
        self.labelWire2 = QtWidgets.QLabel(self.busEditor)
        self.labelWire2.setObjectName("labelWire2")
        self.gridLayout.addWidget(self.labelWire2, 7, 3, 1, 1)
        self.fldComment = QtWidgets.QPlainTextEdit(self.busEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldComment.sizePolicy().hasHeightForWidth())
        self.fldComment.setSizePolicy(sizePolicy)
        self.fldComment.setMaximumSize(QtCore.QSize(16777215, 60))
        self.fldComment.setObjectName("fldComment")
        self.gridLayout.addWidget(self.fldComment, 5, 1, 1, 5)
        self.fldName = QtWidgets.QLineEdit(self.busEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldName.sizePolicy().hasHeightForWidth())
        self.fldName.setSizePolicy(sizePolicy)
        self.fldName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fldName.setMaxLength(16)
        self.fldName.setObjectName("fldName")
        self.gridLayout.addWidget(self.fldName, 1, 1, 1, 2)
        self.labelOBD2 = QtWidgets.QLabel(self.busEditor)
        self.labelOBD2.setObjectName("labelOBD2")
        self.gridLayout.addWidget(self.labelOBD2, 9, 3, 1, 1)
        self.editorCancel = QtWidgets.QPushButton(self.busEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editorCancel.sizePolicy().hasHeightForWidth())
        self.editorCancel.setSizePolicy(sizePolicy)
        self.editorCancel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.editorCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editorCancel.setObjectName("editorCancel")
        self.gridLayout.addWidget(self.editorCancel, 13, 5, 1, 1)
        self.labelComment = QtWidgets.QLabel(self.busEditor)
        self.labelComment.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelComment.setObjectName("labelComment")
        self.gridLayout.addWidget(self.labelComment, 5, 0, 1, 1)
        self.labelSpeed = QtWidgets.QLabel(self.busEditor)
        self.labelSpeed.setObjectName("labelSpeed")
        self.gridLayout.addWidget(self.labelSpeed, 1, 3, 1, 1)
        self.fldSpeed = QtWidgets.QComboBox(self.busEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldSpeed.sizePolicy().hasHeightForWidth())
        self.fldSpeed.setSizePolicy(sizePolicy)
        self.fldSpeed.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fldSpeed.setObjectName("fldSpeed")
        self.gridLayout.addWidget(self.fldSpeed, 1, 4, 1, 2)
        self.fldManufacturer = QtWidgets.QLineEdit(self.busEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldManufacturer.sizePolicy().hasHeightForWidth())
        self.fldManufacturer.setSizePolicy(sizePolicy)
        self.fldManufacturer.setObjectName("fldManufacturer")
        self.gridLayout.addWidget(self.fldManufacturer, 3, 4, 1, 1)
        self.btnDelete = QtWidgets.QPushButton(self.busEditor)
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout.addWidget(self.btnDelete, 13, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.busEditor)
        self.busList = QtWidgets.QWidget(self.tabBus)
        self.busList.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.busList.sizePolicy().hasHeightForWidth())
        self.busList.setSizePolicy(sizePolicy)
        self.busList.setObjectName("busList")
        self.busListLayout = QtWidgets.QGridLayout(self.busList)
        self.busListLayout.setObjectName("busListLayout")
        self.busSpeedTitle = QtWidgets.QLabel(self.busList)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.busSpeedTitle.setFont(font)
        self.busSpeedTitle.setObjectName("busSpeedTitle")
        self.busListLayout.addWidget(self.busSpeedTitle, 0, 1, 1, 1)
        self.busNameTitle = QtWidgets.QLabel(self.busList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.busNameTitle.sizePolicy().hasHeightForWidth())
        self.busNameTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.busNameTitle.setFont(font)
        self.busNameTitle.setObjectName("busNameTitle")
        self.busListLayout.addWidget(self.busNameTitle, 0, 0, 1, 1)
        self.btnAddBus = QtWidgets.QPushButton(self.busList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddBus.sizePolicy().hasHeightForWidth())
        self.btnAddBus.setSizePolicy(sizePolicy)
        self.btnAddBus.setObjectName("btnAddBus")
        self.busListLayout.addWidget(self.btnAddBus, 0, 3, 1, 1)
        self.busColorTitle = QtWidgets.QLabel(self.busList)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.busColorTitle.setFont(font)
        self.busColorTitle.setObjectName("busColorTitle")
        self.busListLayout.addWidget(self.busColorTitle, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.busList)
        self.tabWidget.addTab(self.tabBus, "")
        self.verticalLayout.addWidget(self.tabWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(BUS)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BUS)

    def retranslateUi(self, BUS):
        _translate = QtCore.QCoreApplication.translate
        self.busTitleSpeed.setText(_translate("BUS", "SPEED"))
        self.busTitleIface.setText(_translate("BUS", "IFACE"))
        self.busTitlePreset.setText(_translate("BUS", "BUS"))
        self.busTitleName.setText(_translate("BUS", "LABEL"))
        self.busTitleGw.setText(_translate("BUS", "GW"))
        self.busTitleActive.setText(_translate("BUS", "ACTIVE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIface), _translate("BUS", "INTERFACES"))
        self.labelWire1.setText(_translate("BUS", "WIRE_1_COLOR"))
        self.labelKlnInit.setText(_translate("BUS", "INIT"))
        self.editorSave.setText(_translate("BUS", "SAVE"))
        self.editorSave.setProperty("cssClass", _translate("BUS", "btn-success"))
        self.labelPreset.setText(_translate("BUS", "PRESET"))
        self.labelOBD1.setText(_translate("BUS", "WIRE_1_OBD"))
        self.labelName.setText(_translate("BUS", "NAME"))
        self.labelLinVersion.setText(_translate("BUS", "VERSION"))
        self.labelWire2.setText(_translate("BUS", "WIRE_2_COLOR"))
        self.labelOBD2.setText(_translate("BUS", "WIRE_2_OBD"))
        self.editorCancel.setText(_translate("BUS", "CANCEL"))
        self.editorCancel.setProperty("cssClass", _translate("BUS", "btn-danger"))
        self.labelComment.setText(_translate("BUS", "COMMENT"))
        self.labelSpeed.setText(_translate("BUS", "SPEED"))
        self.btnDelete.setText(_translate("BUS", "DELETE"))
        self.btnDelete.setProperty("cssClass", _translate("BUS", "btn-danger"))
        self.busSpeedTitle.setText(_translate("BUS", "BUS_SPEED"))
        self.busNameTitle.setText(_translate("BUS", "BUS_NAME"))
        self.btnAddBus.setText(_translate("BUS", "ADD_BUS"))
        self.btnAddBus.setProperty("cssClass", _translate("BUS", "btn-success"))
        self.busColorTitle.setText(_translate("BUS", "BUS_WIRE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBus), _translate("BUS", "BUS"))

