# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form-commands.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_COMMAND(object):
    def setupUi(self, COMMAND):
        COMMAND.setObjectName("COMMAND")
        COMMAND.resize(828, 654)
        self.bodyLayout = QtWidgets.QHBoxLayout(COMMAND)
        self.bodyLayout.setContentsMargins(0, 0, 0, 0)
        self.bodyLayout.setObjectName("bodyLayout")
        self.msgManager = QtWidgets.QWidget(COMMAND)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgManager.sizePolicy().hasHeightForWidth())
        self.msgManager.setSizePolicy(sizePolicy)
        self.msgManager.setObjectName("msgManager")
        self.msgManagerLayout = QtWidgets.QVBoxLayout(self.msgManager)
        self.msgManagerLayout.setContentsMargins(-1, 0, -1, 0)
        self.msgManagerLayout.setObjectName("msgManagerLayout")
        self.widgetSelector = QtWidgets.QWidget(self.msgManager)
        self.widgetSelector.setObjectName("widgetSelector")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetSelector)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblSelector = QtWidgets.QLabel(self.widgetSelector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSelector.sizePolicy().hasHeightForWidth())
        self.lblSelector.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSelector.setFont(font)
        self.lblSelector.setObjectName("lblSelector")
        self.horizontalLayout.addWidget(self.lblSelector)
        self.comboCmdSrc = QtWidgets.QComboBox(self.widgetSelector)
        self.comboCmdSrc.setObjectName("comboCmdSrc")
        self.horizontalLayout.addWidget(self.comboCmdSrc)
        self.comboCmdSelector = QtWidgets.QComboBox(self.widgetSelector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCmdSelector.sizePolicy().hasHeightForWidth())
        self.comboCmdSelector.setSizePolicy(sizePolicy)
        self.comboCmdSelector.setObjectName("comboCmdSelector")
        self.horizontalLayout.addWidget(self.comboCmdSelector)
        self.msgManagerLayout.addWidget(self.widgetSelector)
        self.msgLine = QtWidgets.QFrame(self.msgManager)
        self.msgLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.msgLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.msgLine.setObjectName("msgLine")
        self.msgManagerLayout.addWidget(self.msgLine)
        self.lblConstantMsg = QtWidgets.QLabel(self.msgManager)
        self.lblConstantMsg.setObjectName("lblConstantMsg")
        self.msgManagerLayout.addWidget(self.lblConstantMsg)
        self.constantMsg = QtWidgets.QListWidget(self.msgManager)
        self.constantMsg.setMinimumSize(QtCore.QSize(0, 0))
        self.constantMsg.setMaximumSize(QtCore.QSize(16777215, 230))
        self.constantMsg.setDragEnabled(True)
        self.constantMsg.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.constantMsg.setAlternatingRowColors(True)
        self.constantMsg.setObjectName("constantMsg")
        self.msgManagerLayout.addWidget(self.constantMsg)
        self.lblActiveMsg = QtWidgets.QLabel(self.msgManager)
        self.lblActiveMsg.setObjectName("lblActiveMsg")
        self.msgManagerLayout.addWidget(self.lblActiveMsg)
        self.activeMsg = QtWidgets.QListWidget(self.msgManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activeMsg.sizePolicy().hasHeightForWidth())
        self.activeMsg.setSizePolicy(sizePolicy)
        self.activeMsg.setMinimumSize(QtCore.QSize(0, 290))
        self.activeMsg.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.activeMsg.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.activeMsg.setDragEnabled(True)
        self.activeMsg.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.activeMsg.setAlternatingRowColors(True)
        self.activeMsg.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.activeMsg.setObjectName("activeMsg")
        self.msgManagerLayout.addWidget(self.activeMsg)
        self.widget = QtWidgets.QWidget(self.msgManager)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAddConstant = QtWidgets.QPushButton(self.widget)
        self.btnAddConstant.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAddConstant.setObjectName("btnAddConstant")
        self.horizontalLayout_2.addWidget(self.btnAddConstant)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.btnAddActive = QtWidgets.QPushButton(self.widget)
        self.btnAddActive.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAddActive.setObjectName("btnAddActive")
        self.horizontalLayout_2.addWidget(self.btnAddActive)
        self.btnAddPause = QtWidgets.QPushButton(self.widget)
        self.btnAddPause.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAddPause.setObjectName("btnAddPause")
        self.horizontalLayout_2.addWidget(self.btnAddPause)
        self.msgManagerLayout.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.msgManagerLayout.addItem(spacerItem)
        self.bodyLayout.addWidget(self.msgManager)
        self.editor = QtWidgets.QWidget(COMMAND)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editor.sizePolicy().hasHeightForWidth())
        self.editor.setSizePolicy(sizePolicy)
        self.editor.setObjectName("editor")
        self.signalEditorLayout = QtWidgets.QVBoxLayout(self.editor)
        self.signalEditorLayout.setContentsMargins(0, 0, 0, 0)
        self.signalEditorLayout.setSpacing(0)
        self.signalEditorLayout.setObjectName("signalEditorLayout")
        self.cardOpt = QtWidgets.QWidget(self.editor)
        self.cardOpt.setProperty("cssClass", "")
        self.cardOpt.setObjectName("cardOpt")
        self.mainLayout = QtWidgets.QVBoxLayout(self.cardOpt)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.cardOptHeade = QtWidgets.QWidget(self.cardOpt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardOptHeade.sizePolicy().hasHeightForWidth())
        self.cardOptHeade.setSizePolicy(sizePolicy)
        self.cardOptHeade.setStyleSheet("")
        self.cardOptHeade.setObjectName("cardOptHeade")
        self.cardDisplayHLayout_2 = QtWidgets.QHBoxLayout(self.cardOptHeade)
        self.cardDisplayHLayout_2.setObjectName("cardDisplayHLayout_2")
        self.titleCmdOpt = QtWidgets.QLabel(self.cardOptHeade)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleCmdOpt.sizePolicy().hasHeightForWidth())
        self.titleCmdOpt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titleCmdOpt.setFont(font)
        self.titleCmdOpt.setStyleSheet("background:none;\n"
"border:0;\n"
"border-radius:0;")
        self.titleCmdOpt.setObjectName("titleCmdOpt")
        self.cardDisplayHLayout_2.addWidget(self.titleCmdOpt)
        self.btnNewCmd = QtWidgets.QPushButton(self.cardOptHeade)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewCmd.sizePolicy().hasHeightForWidth())
        self.btnNewCmd.setSizePolicy(sizePolicy)
        self.btnNewCmd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNewCmd.setObjectName("btnNewCmd")
        self.cardDisplayHLayout_2.addWidget(self.btnNewCmd)
        self.mainLayout.addWidget(self.cardOptHeade)
        self.cardOptMsg = QtWidgets.QWidget(self.cardOpt)
        self.cardOptMsg.setObjectName("cardOptMsg")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.cardOptMsg)
        self.verticalLayout.setContentsMargins(9, 6, 9, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cardCmdOpt = QtWidgets.QWidget(self.cardOptMsg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardCmdOpt.sizePolicy().hasHeightForWidth())
        self.cardCmdOpt.setSizePolicy(sizePolicy)
        self.cardCmdOpt.setStyleSheet("")
        self.cardCmdOpt.setProperty("cssClass", "")
        self.cardCmdOpt.setObjectName("cardCmdOpt")
        self.formDisplayLayout_2 = QtWidgets.QFormLayout(self.cardCmdOpt)
        self.formDisplayLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formDisplayLayout_2.setVerticalSpacing(6)
        self.formDisplayLayout_2.setObjectName("formDisplayLayout_2")
        self.lblName = QtWidgets.QLabel(self.cardCmdOpt)
        self.lblName.setObjectName("lblName")
        self.formDisplayLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblName)
        self.fldName = QtWidgets.QLineEdit(self.cardCmdOpt)
        self.fldName.setObjectName("fldName")
        self.formDisplayLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fldName)
        self.lblRepeat = QtWidgets.QLabel(self.cardCmdOpt)
        self.lblRepeat.setObjectName("lblRepeat")
        self.formDisplayLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblRepeat)
        self.fldRepeat = QtWidgets.QLineEdit(self.cardCmdOpt)
        self.fldRepeat.setMaximumSize(QtCore.QSize(40, 16777215))
        self.fldRepeat.setMaxLength(3)
        self.fldRepeat.setObjectName("fldRepeat")
        self.formDisplayLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fldRepeat)
        self.verticalLayout.addWidget(self.cardCmdOpt)
        self.errorMsg = QtWidgets.QLabel(self.cardOptMsg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errorMsg.sizePolicy().hasHeightForWidth())
        self.errorMsg.setSizePolicy(sizePolicy)
        self.errorMsg.setWordWrap(True)
        self.errorMsg.setObjectName("errorMsg")
        self.verticalLayout.addWidget(self.errorMsg)
        self.btnPlay = QtWidgets.QPushButton(self.cardOptMsg)
        self.btnPlay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPlay.setObjectName("btnPlay")
        self.verticalLayout.addWidget(self.btnPlay)
        self.tabWidget = QtWidgets.QTabWidget(self.cardOptMsg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabHelp = QtWidgets.QWidget()
        self.tabHelp.setObjectName("tabHelp")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabHelp)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fldHelp = QtWidgets.QPlainTextEdit(self.tabHelp)
        self.fldHelp.setReadOnly(True)
        self.fldHelp.setObjectName("fldHelp")
        self.verticalLayout_3.addWidget(self.fldHelp)
        self.tabWidget.addTab(self.tabHelp, "")
        self.tabFollow = QtWidgets.QWidget()
        self.tabFollow.setObjectName("tabFollow")
        self.formLayout = QtWidgets.QFormLayout(self.tabFollow)
        self.formLayout.setContentsMargins(4, -1, 4, -1)
        self.formLayout.setObjectName("formLayout")
        self.tabWidget.addTab(self.tabFollow, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.btnImport = QtWidgets.QPushButton(self.cardOptMsg)
        self.btnImport.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnImport.setObjectName("btnImport")
        self.verticalLayout.addWidget(self.btnImport)
        self.btnShare = QtWidgets.QPushButton(self.cardOptMsg)
        self.btnShare.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnShare.setObjectName("btnShare")
        self.verticalLayout.addWidget(self.btnShare)
        self.btnSave = QtWidgets.QPushButton(self.cardOptMsg)
        self.btnSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout.addWidget(self.btnSave)
        self.btnDelete = QtWidgets.QPushButton(self.cardOptMsg)
        self.btnDelete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDelete.setObjectName("btnDelete")
        self.verticalLayout.addWidget(self.btnDelete)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.mainLayout.addWidget(self.cardOptMsg)
        self.signalEditorLayout.addWidget(self.cardOpt)
        self.bodyLayout.addWidget(self.editor)

        self.retranslateUi(COMMAND)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(COMMAND)
        COMMAND.setTabOrder(self.activeMsg, self.comboCmdSelector)
        COMMAND.setTabOrder(self.comboCmdSelector, self.btnNewCmd)
        COMMAND.setTabOrder(self.btnNewCmd, self.fldName)
        COMMAND.setTabOrder(self.fldName, self.tabWidget)

    def retranslateUi(self, COMMAND):
        _translate = QtCore.QCoreApplication.translate
        COMMAND.setWindowTitle(_translate("COMMAND", "Form"))
        self.lblSelector.setText(_translate("COMMAND", "CMD_SELECTOR"))
        self.lblConstantMsg.setText(_translate("COMMAND", "CONSTANT_MSG"))
        self.lblActiveMsg.setText(_translate("COMMAND", "ACTIVE_MSG"))
        self.btnAddConstant.setText(_translate("COMMAND", "ADD_CONSTANT"))
        self.btnAddConstant.setProperty("cssClass", _translate("COMMAND", "btn-primary"))
        self.btnAddActive.setText(_translate("COMMAND", "ADD_ACTIVE"))
        self.btnAddActive.setProperty("cssClass", _translate("COMMAND", "btn-primary"))
        self.btnAddPause.setText(_translate("COMMAND", "ADD_PAUSE"))
        self.btnAddPause.setProperty("cssClass", _translate("COMMAND", "btn-primary"))
        self.editor.setProperty("cssClass", _translate("COMMAND", "card"))
        self.cardOptHeade.setProperty("cssClass", _translate("COMMAND", "cardHeader"))
        self.titleCmdOpt.setText(_translate("COMMAND", "CMD_OPTIONS"))
        self.titleCmdOpt.setProperty("cssClass", _translate("COMMAND", "cardTitle"))
        self.btnNewCmd.setText(_translate("COMMAND", "NEW_CMD"))
        self.btnNewCmd.setProperty("cssClass", _translate("COMMAND", "btn-primary"))
        self.cardOptMsg.setProperty("cssClass", _translate("COMMAND", "cardBody"))
        self.lblName.setText(_translate("COMMAND", "NAME"))
        self.lblRepeat.setText(_translate("COMMAND", "REPEAT"))
        self.errorMsg.setText(_translate("COMMAND", "ERROR_MSG"))
        self.errorMsg.setProperty("cssClass", _translate("COMMAND", "text-danger"))
        self.btnPlay.setText(_translate("COMMAND", "PLAY_CMD"))
        self.btnPlay.setProperty("cssClass", _translate("COMMAND", "btn-disabled"))
        self.fldHelp.setPlainText(_translate("COMMAND", "HELP_TXT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHelp), _translate("COMMAND", "HELP_OPT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFollow), _translate("COMMAND", "FOLLOW_OPT"))
        self.btnImport.setText(_translate("COMMAND", "IMPORT"))
        self.btnImport.setProperty("cssClass", _translate("COMMAND", "btn-success"))
        self.btnShare.setText(_translate("COMMAND", "SHARE"))
        self.btnShare.setProperty("cssClass", _translate("COMMAND", "btn-secondary"))
        self.btnSave.setText(_translate("COMMAND", "SAVE"))
        self.btnSave.setProperty("cssClass", _translate("COMMAND", "btn-disabled"))
        self.btnDelete.setText(_translate("COMMAND", "DELETE"))
        self.btnDelete.setProperty("cssClass", _translate("COMMAND", "btn-danger"))

