# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form-devices.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DEVICES(object):
    def setupUi(self, DEVICES):
        DEVICES.setObjectName("DEVICES")
        DEVICES.resize(600, 217)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DEVICES.sizePolicy().hasHeightForWidth())
        DEVICES.setSizePolicy(sizePolicy)
        DEVICES.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(DEVICES)
        self.verticalLayout.setObjectName("verticalLayout")
        self.interfaceTitle = QtWidgets.QLabel(DEVICES)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interfaceTitle.sizePolicy().hasHeightForWidth())
        self.interfaceTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.interfaceTitle.setFont(font)
        self.interfaceTitle.setObjectName("interfaceTitle")
        self.verticalLayout.addWidget(self.interfaceTitle)
        self.ifaceGridWidget = QtWidgets.QWidget(DEVICES)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ifaceGridWidget.sizePolicy().hasHeightForWidth())
        self.ifaceGridWidget.setSizePolicy(sizePolicy)
        self.ifaceGridWidget.setObjectName("ifaceGridWidget")
        self.ifaceGridLayout = QtWidgets.QGridLayout(self.ifaceGridWidget)
        self.ifaceGridLayout.setObjectName("ifaceGridLayout")
        self.ifaceTitleAdd = QtWidgets.QLabel(self.ifaceGridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ifaceTitleAdd.sizePolicy().hasHeightForWidth())
        self.ifaceTitleAdd.setSizePolicy(sizePolicy)
        self.ifaceTitleAdd.setMinimumSize(QtCore.QSize(40, 0))
        self.ifaceTitleAdd.setText("")
        self.ifaceTitleAdd.setObjectName("ifaceTitleAdd")
        self.ifaceGridLayout.addWidget(self.ifaceTitleAdd, 0, 3, 1, 1)
        self.ifaceTitlePort = QtWidgets.QLabel(self.ifaceGridWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ifaceTitlePort.setFont(font)
        self.ifaceTitlePort.setObjectName("ifaceTitlePort")
        self.ifaceGridLayout.addWidget(self.ifaceTitlePort, 0, 1, 1, 1)
        self.ifaceTitleIface = QtWidgets.QLabel(self.ifaceGridWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ifaceTitleIface.setFont(font)
        self.ifaceTitleIface.setObjectName("ifaceTitleIface")
        self.ifaceGridLayout.addWidget(self.ifaceTitleIface, 0, 2, 1, 1)
        self.ifaceTitleDevice = QtWidgets.QLabel(self.ifaceGridWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ifaceTitleDevice.setFont(font)
        self.ifaceTitleDevice.setObjectName("ifaceTitleDevice")
        self.ifaceGridLayout.addWidget(self.ifaceTitleDevice, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.ifaceGridWidget)
        self.split = QtWidgets.QFrame(DEVICES)
        self.split.setFrameShape(QtWidgets.QFrame.HLine)
        self.split.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.split.setObjectName("split")
        self.verticalLayout.addWidget(self.split)
        self.deviceTitle = QtWidgets.QLabel(DEVICES)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deviceTitle.sizePolicy().hasHeightForWidth())
        self.deviceTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.deviceTitle.setFont(font)
        self.deviceTitle.setObjectName("deviceTitle")
        self.verticalLayout.addWidget(self.deviceTitle)
        self.deviceGridWidget = QtWidgets.QWidget(DEVICES)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deviceGridWidget.sizePolicy().hasHeightForWidth())
        self.deviceGridWidget.setSizePolicy(sizePolicy)
        self.deviceGridWidget.setObjectName("deviceGridWidget")
        self.deviceGridLayout = QtWidgets.QGridLayout(self.deviceGridWidget)
        self.deviceGridLayout.setObjectName("deviceGridLayout")
        self.devTitlePort = QtWidgets.QLabel(self.deviceGridWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.devTitlePort.setFont(font)
        self.devTitlePort.setObjectName("devTitlePort")
        self.deviceGridLayout.addWidget(self.devTitlePort, 0, 1, 1, 1)
        self.devTitleDev = QtWidgets.QLabel(self.deviceGridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devTitleDev.sizePolicy().hasHeightForWidth())
        self.devTitleDev.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.devTitleDev.setFont(font)
        self.devTitleDev.setObjectName("devTitleDev")
        self.deviceGridLayout.addWidget(self.devTitleDev, 0, 0, 1, 1)
        self.devTitleAdd = QtWidgets.QLabel(self.deviceGridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devTitleAdd.sizePolicy().hasHeightForWidth())
        self.devTitleAdd.setSizePolicy(sizePolicy)
        self.devTitleAdd.setMinimumSize(QtCore.QSize(40, 0))
        self.devTitleAdd.setText("")
        self.devTitleAdd.setObjectName("devTitleAdd")
        self.deviceGridLayout.addWidget(self.devTitleAdd, 0, 4, 1, 1)
        self.devTitlePerm = QtWidgets.QLabel(self.deviceGridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devTitlePerm.sizePolicy().hasHeightForWidth())
        self.devTitlePerm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.devTitlePerm.setFont(font)
        self.devTitlePerm.setObjectName("devTitlePerm")
        self.deviceGridLayout.addWidget(self.devTitlePerm, 0, 3, 1, 1)
        self.devTitleRef = QtWidgets.QLabel(self.deviceGridWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.devTitleRef.setFont(font)
        self.devTitleRef.setObjectName("devTitleRef")
        self.deviceGridLayout.addWidget(self.devTitleRef, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.deviceGridWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(DEVICES)
        QtCore.QMetaObject.connectSlotsByName(DEVICES)

    def retranslateUi(self, DEVICES):
        _translate = QtCore.QCoreApplication.translate
        self.interfaceTitle.setText(_translate("DEVICES", "IFACES_AVAILABLE"))
        self.ifaceTitlePort.setText(_translate("DEVICES", "PORT"))
        self.ifaceTitleIface.setText(_translate("DEVICES", "IFACES"))
        self.ifaceTitleDevice.setText(_translate("DEVICES", "IFACE"))
        self.deviceTitle.setText(_translate("DEVICES", "DEVICES_AVAILABLE"))
        self.devTitlePort.setText(_translate("DEVICES", "PORT"))
        self.devTitleDev.setText(_translate("DEVICES", "EQT"))
        self.devTitlePerm.setText(_translate("DEVICES", "AUTO"))
        self.devTitleRef.setText(_translate("DEVICES", "REF"))

