# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1112, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainMenu = QtWidgets.QWidget(self.centralwidget)
        self.mainMenu.setEnabled(True)
        self.mainMenu.setAutoFillBackground(False)
        self.mainMenu.setStyleSheet("")
        self.mainMenu.setObjectName("mainMenu")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.mainMenu)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnMainMenu = QtWidgets.QPushButton(self.mainMenu)
        self.btnMainMenu.setMinimumSize(QtCore.QSize(32, 32))
        self.btnMainMenu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMainMenu.setText("")
        self.btnMainMenu.setIconSize(QtCore.QSize(32, 32))
        self.btnMainMenu.setObjectName("btnMainMenu")
        self.horizontalLayout_5.addWidget(self.btnMainMenu)
        self.label = QtWidgets.QLabel(self.mainMenu)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.btnAnalysis = QtWidgets.QPushButton(self.mainMenu)
        self.btnAnalysis.setMinimumSize(QtCore.QSize(32, 32))
        self.btnAnalysis.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAnalysis.setText("")
        self.btnAnalysis.setIconSize(QtCore.QSize(32, 32))
        self.btnAnalysis.setObjectName("btnAnalysis")
        self.horizontalLayout_5.addWidget(self.btnAnalysis)
        self.btnDevices = QtWidgets.QPushButton(self.mainMenu)
        self.btnDevices.setMinimumSize(QtCore.QSize(32, 32))
        self.btnDevices.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDevices.setStyleSheet("")
        self.btnDevices.setText("")
        self.btnDevices.setIconSize(QtCore.QSize(32, 32))
        self.btnDevices.setObjectName("btnDevices")
        self.horizontalLayout_5.addWidget(self.btnDevices)
        self.btnServer = QtWidgets.QPushButton(self.mainMenu)
        self.btnServer.setMinimumSize(QtCore.QSize(32, 32))
        self.btnServer.setSizeIncrement(QtCore.QSize(32, 32))
        self.btnServer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnServer.setText("")
        self.btnServer.setIconSize(QtCore.QSize(32, 32))
        self.btnServer.setObjectName("btnServer")
        self.horizontalLayout_5.addWidget(self.btnServer)
        self.btnNotification = QtWidgets.QPushButton(self.mainMenu)
        self.btnNotification.setMinimumSize(QtCore.QSize(32, 32))
        self.btnNotification.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNotification.setText("")
        self.btnNotification.setIconSize(QtCore.QSize(32, 32))
        self.btnNotification.setObjectName("btnNotification")
        self.horizontalLayout_5.addWidget(self.btnNotification)
        self.btnConfig = QtWidgets.QPushButton(self.mainMenu)
        self.btnConfig.setMinimumSize(QtCore.QSize(32, 32))
        self.btnConfig.setText("")
        self.btnConfig.setIconSize(QtCore.QSize(32, 32))
        self.btnConfig.setObjectName("btnConfig")
        self.horizontalLayout_5.addWidget(self.btnConfig)
        self.btnProfile = QtWidgets.QPushButton(self.mainMenu)
        self.btnProfile.setMinimumSize(QtCore.QSize(32, 32))
        self.btnProfile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnProfile.setText("")
        self.btnProfile.setIconSize(QtCore.QSize(32, 32))
        self.btnProfile.setObjectName("btnProfile")
        self.horizontalLayout_5.addWidget(self.btnProfile)
        self.verticalLayout.addWidget(self.mainMenu)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.loginPage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginCard = QtWidgets.QWidget(self.loginPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginCard.sizePolicy().hasHeightForWidth())
        self.loginCard.setSizePolicy(sizePolicy)
        self.loginCard.setMaximumSize(QtCore.QSize(500, 16777215))
        self.loginCard.setObjectName("loginCard")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.loginCard)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.loginCardHeader = QtWidgets.QWidget(self.loginCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginCardHeader.sizePolicy().hasHeightForWidth())
        self.loginCardHeader.setSizePolicy(sizePolicy)
        self.loginCardHeader.setMinimumSize(QtCore.QSize(0, 0))
        self.loginCardHeader.setObjectName("loginCardHeader")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.loginCardHeader)
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 9)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.loginTitle = QtWidgets.QLabel(self.loginCardHeader)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loginTitle.setFont(font)
        self.loginTitle.setObjectName("loginTitle")
        self.horizontalLayout_2.addWidget(self.loginTitle)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.loginCardHeader)
        self.loginLogoSpacer = QtWidgets.QWidget(self.loginCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginLogoSpacer.sizePolicy().hasHeightForWidth())
        self.loginLogoSpacer.setSizePolicy(sizePolicy)
        self.loginLogoSpacer.setMinimumSize(QtCore.QSize(0, 0))
        self.loginLogoSpacer.setStyleSheet("")
        self.loginLogoSpacer.setObjectName("loginLogoSpacer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.loginLogoSpacer)
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.loginLogo = QtWidgets.QPushButton(self.loginLogoSpacer)
        self.loginLogo.setEnabled(False)
        self.loginLogo.setText("")
        self.loginLogo.setIconSize(QtCore.QSize(48, 48))
        self.loginLogo.setObjectName("loginLogo")
        self.horizontalLayout_3.addWidget(self.loginLogo)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.loginLogoSpacer)
        self.loginBody = QtWidgets.QWidget(self.loginCard)
        self.loginBody.setObjectName("loginBody")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.loginBody)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.loginForm = QtWidgets.QWidget(self.loginBody)
        self.loginForm.setObjectName("loginForm")
        self.formLayout = QtWidgets.QFormLayout(self.loginForm)
        self.formLayout.setObjectName("formLayout")
        self.labelUsername = QtWidgets.QLabel(self.loginForm)
        self.labelUsername.setObjectName("labelUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelUsername)
        self.fldUsername = QtWidgets.QLineEdit(self.loginForm)
        self.fldUsername.setObjectName("fldUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fldUsername)
        self.labelPassword = QtWidgets.QLabel(self.loginForm)
        self.labelPassword.setObjectName("labelPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelPassword)
        self.fldPassword = QtWidgets.QLineEdit(self.loginForm)
        self.fldPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.fldPassword.setObjectName("fldPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fldPassword)
        self.btnLogin = QtWidgets.QPushButton(self.loginForm)
        self.btnLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLogin.setObjectName("btnLogin")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.btnLogin)
        self.errorMsg = QtWidgets.QLabel(self.loginForm)
        self.errorMsg.setEnabled(True)
        self.errorMsg.setWordWrap(True)
        self.errorMsg.setObjectName("errorMsg")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.errorMsg)
        self.fldConfirmPassword = QtWidgets.QLineEdit(self.loginForm)
        self.fldConfirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.fldConfirmPassword.setObjectName("fldConfirmPassword")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fldConfirmPassword)
        self.newUserMsg = QtWidgets.QLabel(self.loginForm)
        self.newUserMsg.setWordWrap(True)
        self.newUserMsg.setObjectName("newUserMsg")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.newUserMsg)
        self.labelProfileName = QtWidgets.QLabel(self.loginForm)
        self.labelProfileName.setObjectName("labelProfileName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelProfileName)
        self.fldProfileName = QtWidgets.QLineEdit(self.loginForm)
        self.fldProfileName.setObjectName("fldProfileName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fldProfileName)
        self.horizontalLayout_6.addWidget(self.loginForm)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_3.addWidget(self.loginBody)
        self.horizontalLayout.addWidget(self.loginCard)
        self.stackedWidget.addWidget(self.loginPage)
        self.dashboardPage = QtWidgets.QWidget()
        self.dashboardPage.setObjectName("dashboardPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dashboardPage)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dashBtn = QtWidgets.QWidget(self.dashboardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dashBtn.sizePolicy().hasHeightForWidth())
        self.dashBtn.setSizePolicy(sizePolicy)
        self.dashBtn.setObjectName("dashBtn")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.dashBtn)
        self.horizontalLayout_4.setContentsMargins(-1, 16, -1, 12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnNewAnalysis = QtWidgets.QPushButton(self.dashBtn)
        self.btnNewAnalysis.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNewAnalysis.setObjectName("btnNewAnalysis")
        self.horizontalLayout_4.addWidget(self.btnNewAnalysis)
        self.btnLoadAnalysis = QtWidgets.QPushButton(self.dashBtn)
        self.btnLoadAnalysis.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLoadAnalysis.setObjectName("btnLoadAnalysis")
        self.horizontalLayout_4.addWidget(self.btnLoadAnalysis)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_2.addWidget(self.dashBtn)
        self.dashBody = QtWidgets.QWidget(self.dashboardPage)
        self.dashBody.setObjectName("dashBody")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.dashBody)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.leftDash = QtWidgets.QWidget(self.dashBody)
        self.leftDash.setObjectName("leftDash")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.leftDash)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cardAnalysis = QtWidgets.QWidget(self.leftDash)
        self.cardAnalysis.setObjectName("cardAnalysis")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.cardAnalysis)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cardTitleAnalysis = QtWidgets.QWidget(self.cardAnalysis)
        self.cardTitleAnalysis.setObjectName("cardTitleAnalysis")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.cardTitleAnalysis)
        self.horizontalLayout_8.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.titleAnalysis = QtWidgets.QLabel(self.cardTitleAnalysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleAnalysis.sizePolicy().hasHeightForWidth())
        self.titleAnalysis.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titleAnalysis.setFont(font)
        self.titleAnalysis.setObjectName("titleAnalysis")
        self.horizontalLayout_8.addWidget(self.titleAnalysis)
        self.verticalLayout_5.addWidget(self.cardTitleAnalysis)
        self.cardBodyAnalysis = QtWidgets.QWidget(self.cardAnalysis)
        self.cardBodyAnalysis.setObjectName("cardBodyAnalysis")
        self.analysisGridLayout = QtWidgets.QGridLayout(self.cardBodyAnalysis)
        self.analysisGridLayout.setContentsMargins(-1, 9, -1, -1)
        self.analysisGridLayout.setVerticalSpacing(12)
        self.analysisGridLayout.setObjectName("analysisGridLayout")
        self.lastAnalysisModelTitle = QtWidgets.QLabel(self.cardBodyAnalysis)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lastAnalysisModelTitle.setFont(font)
        self.lastAnalysisModelTitle.setObjectName("lastAnalysisModelTitle")
        self.analysisGridLayout.addWidget(self.lastAnalysisModelTitle, 0, 1, 1, 1)
        self.lastAnalysisPrivacyTitle = QtWidgets.QLabel(self.cardBodyAnalysis)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lastAnalysisPrivacyTitle.setFont(font)
        self.lastAnalysisPrivacyTitle.setObjectName("lastAnalysisPrivacyTitle")
        self.analysisGridLayout.addWidget(self.lastAnalysisPrivacyTitle, 0, 3, 1, 1)
        self.lastAnalysisDateTitle = QtWidgets.QLabel(self.cardBodyAnalysis)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lastAnalysisDateTitle.setFont(font)
        self.lastAnalysisDateTitle.setObjectName("lastAnalysisDateTitle")
        self.analysisGridLayout.addWidget(self.lastAnalysisDateTitle, 0, 2, 1, 1)
        self.lastAnalysisBtnTitle = QtWidgets.QLabel(self.cardBodyAnalysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastAnalysisBtnTitle.sizePolicy().hasHeightForWidth())
        self.lastAnalysisBtnTitle.setSizePolicy(sizePolicy)
        self.lastAnalysisBtnTitle.setText("")
        self.lastAnalysisBtnTitle.setObjectName("lastAnalysisBtnTitle")
        self.analysisGridLayout.addWidget(self.lastAnalysisBtnTitle, 0, 4, 1, 1)
        self.lastAnalysisIconTitle = QtWidgets.QLabel(self.cardBodyAnalysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastAnalysisIconTitle.sizePolicy().hasHeightForWidth())
        self.lastAnalysisIconTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lastAnalysisIconTitle.setFont(font)
        self.lastAnalysisIconTitle.setObjectName("lastAnalysisIconTitle")
        self.analysisGridLayout.addWidget(self.lastAnalysisIconTitle, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.cardBodyAnalysis)
        self.verticalLayout_4.addWidget(self.cardAnalysis)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.horizontalLayout_7.addWidget(self.leftDash)
        self.rightDash = QtWidgets.QWidget(self.dashBody)
        self.rightDash.setObjectName("rightDash")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.rightDash)
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cardStat = QtWidgets.QWidget(self.rightDash)
        self.cardStat.setObjectName("cardStat")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.cardStat)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cardTitleStat = QtWidgets.QWidget(self.cardStat)
        self.cardTitleStat.setObjectName("cardTitleStat")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.cardTitleStat)
        self.horizontalLayout_9.setContentsMargins(5, -1, -1, 5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.titleStat = QtWidgets.QLabel(self.cardTitleStat)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titleStat.setFont(font)
        self.titleStat.setObjectName("titleStat")
        self.horizontalLayout_9.addWidget(self.titleStat)
        self.verticalLayout_7.addWidget(self.cardTitleStat)
        self.cardBodyStat = QtWidgets.QWidget(self.cardStat)
        self.cardBodyStat.setObjectName("cardBodyStat")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.cardBodyStat)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.cardBodyStat)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_8.addWidget(self.pushButton_4)
        self.stat = QtWidgets.QTextEdit(self.cardBodyStat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stat.sizePolicy().hasHeightForWidth())
        self.stat.setSizePolicy(sizePolicy)
        self.stat.setObjectName("stat")
        self.verticalLayout_8.addWidget(self.stat)
        self.verticalLayout_7.addWidget(self.cardBodyStat)
        self.verticalLayout_6.addWidget(self.cardStat)
        self.cardServer = QtWidgets.QWidget(self.rightDash)
        self.cardServer.setObjectName("cardServer")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.cardServer)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.cardTitleServer = QtWidgets.QWidget(self.cardServer)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cardTitleServer.setFont(font)
        self.cardTitleServer.setObjectName("cardTitleServer")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.cardTitleServer)
        self.horizontalLayout_10.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.cardTitleServer)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.verticalLayout_9.addWidget(self.cardTitleServer)
        self.cardBodyServer = QtWidgets.QWidget(self.cardServer)
        self.cardBodyServer.setObjectName("cardBodyServer")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.cardBodyServer)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_3 = QtWidgets.QPushButton(self.cardBodyServer)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_10.addWidget(self.pushButton_3)
        self.srv = QtWidgets.QTextEdit(self.cardBodyServer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srv.sizePolicy().hasHeightForWidth())
        self.srv.setSizePolicy(sizePolicy)
        self.srv.setObjectName("srv")
        self.verticalLayout_10.addWidget(self.srv)
        self.verticalLayout_9.addWidget(self.cardBodyServer)
        self.verticalLayout_6.addWidget(self.cardServer)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.horizontalLayout_7.addWidget(self.rightDash)
        self.verticalLayout_2.addWidget(self.dashBody)
        self.stackedWidget.addWidget(self.dashboardPage)
        self.analysisPage = QtWidgets.QWidget()
        self.analysisPage.setObjectName("analysisPage")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.analysisPage)
        self.verticalLayout_13.setSpacing(4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.anaysisParam = QtWidgets.QWidget(self.analysisPage)
        self.anaysisParam.setStyleSheet("border-bottom:1px solid #E2E2E2;\n"
"margin-left:0.5em;\n"
"margin-right:0.5em;")
        self.anaysisParam.setObjectName("anaysisParam")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.anaysisParam)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.vehicleTitle = QtWidgets.QLabel(self.anaysisParam)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.vehicleTitle.setFont(font)
        self.vehicleTitle.setObjectName("vehicleTitle")
        self.horizontalLayout_15.addWidget(self.vehicleTitle)
        self.btnEditVehicle = QtWidgets.QPushButton(self.anaysisParam)
        self.btnEditVehicle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEditVehicle.setText("")
        self.btnEditVehicle.setObjectName("btnEditVehicle")
        self.horizontalLayout_15.addWidget(self.btnEditVehicle)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.verticalLayout_13.addWidget(self.anaysisParam)
        self.actionMenu = QtWidgets.QWidget(self.analysisPage)
        self.actionMenu.setObjectName("actionMenu")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.actionMenu)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.btnBusCan = QtWidgets.QPushButton(self.actionMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBusCan.sizePolicy().hasHeightForWidth())
        self.btnBusCan.setSizePolicy(sizePolicy)
        self.btnBusCan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/icons16/application-terminal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBusCan.setIcon(icon)
        self.btnBusCan.setObjectName("btnBusCan")
        self.horizontalLayout_17.addWidget(self.btnBusCan)
        self.btnBusLin = QtWidgets.QPushButton(self.actionMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBusLin.sizePolicy().hasHeightForWidth())
        self.btnBusLin.setSizePolicy(sizePolicy)
        self.btnBusLin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBusLin.setObjectName("btnBusLin")
        self.horizontalLayout_17.addWidget(self.btnBusLin)
        self.btnBusKln = QtWidgets.QPushButton(self.actionMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBusKln.sizePolicy().hasHeightForWidth())
        self.btnBusKln.setSizePolicy(sizePolicy)
        self.btnBusKln.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBusKln.setObjectName("btnBusKln")
        self.horizontalLayout_17.addWidget(self.btnBusKln)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem11)
        self.btnMap = QtWidgets.QPushButton(self.actionMenu)
        self.btnMap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMap.setObjectName("btnMap")
        self.horizontalLayout_17.addWidget(self.btnMap)
        self.btnCmdEditor = QtWidgets.QPushButton(self.actionMenu)
        self.btnCmdEditor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCmdEditor.setToolTip("")
        self.btnCmdEditor.setObjectName("btnCmdEditor")
        self.horizontalLayout_17.addWidget(self.btnCmdEditor)
        self.btnNotes = QtWidgets.QPushButton(self.actionMenu)
        self.btnNotes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNotes.setObjectName("btnNotes")
        self.horizontalLayout_17.addWidget(self.btnNotes)
        self.btnShowRightMenu = QtWidgets.QPushButton(self.actionMenu)
        self.btnShowRightMenu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnShowRightMenu.setToolTip("")
        self.btnShowRightMenu.setObjectName("btnShowRightMenu")
        self.horizontalLayout_17.addWidget(self.btnShowRightMenu)
        self.verticalLayout_13.addWidget(self.actionMenu)
        self.body = QtWidgets.QWidget(self.analysisPage)
        self.body.setObjectName("body")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.body)
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, 4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.msgTable = TableView(self.body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgTable.sizePolicy().hasHeightForWidth())
        self.msgTable.setSizePolicy(sizePolicy)
        self.msgTable.setMinimumSize(QtCore.QSize(760, 0))
        self.msgTable.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.msgTable.setAlternatingRowColors(True)
        self.msgTable.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.msgTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.msgTable.setSortingEnabled(True)
        self.msgTable.setCornerButtonEnabled(True)
        self.msgTable.setObjectName("msgTable")
        self.horizontalLayout_11.addWidget(self.msgTable)
        self.rightMenu = QtWidgets.QScrollArea(self.body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightMenu.sizePolicy().hasHeightForWidth())
        self.rightMenu.setSizePolicy(sizePolicy)
        self.rightMenu.setStyleSheet("")
        self.rightMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightMenu.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.rightMenu.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rightMenu.setWidgetResizable(True)
        self.rightMenu.setObjectName("rightMenu")
        self.rightMenu2 = QtWidgets.QWidget()
        self.rightMenu2.setGeometry(QtCore.QRect(0, 0, 292, 644))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightMenu2.sizePolicy().hasHeightForWidth())
        self.rightMenu2.setSizePolicy(sizePolicy)
        self.rightMenu2.setAutoFillBackground(True)
        self.rightMenu2.setStyleSheet("")
        self.rightMenu2.setObjectName("rightMenu2")
        self.rightMenuLayout = QtWidgets.QVBoxLayout(self.rightMenu2)
        self.rightMenuLayout.setContentsMargins(0, 0, 0, 0)
        self.rightMenuLayout.setSpacing(3)
        self.rightMenuLayout.setObjectName("rightMenuLayout")
        self.cardDisplay = QtWidgets.QWidget(self.rightMenu2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardDisplay.sizePolicy().hasHeightForWidth())
        self.cardDisplay.setSizePolicy(sizePolicy)
        self.cardDisplay.setObjectName("cardDisplay")
        self.cardDisplayLayout = QtWidgets.QVBoxLayout(self.cardDisplay)
        self.cardDisplayLayout.setContentsMargins(-1, 0, -1, 3)
        self.cardDisplayLayout.setSpacing(0)
        self.cardDisplayLayout.setObjectName("cardDisplayLayout")
        self.cardHeaderDisplay = QtWidgets.QWidget(self.cardDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardHeaderDisplay.sizePolicy().hasHeightForWidth())
        self.cardHeaderDisplay.setSizePolicy(sizePolicy)
        self.cardHeaderDisplay.setStyleSheet("")
        self.cardHeaderDisplay.setObjectName("cardHeaderDisplay")
        self.cardDisplayHLayout = QtWidgets.QHBoxLayout(self.cardHeaderDisplay)
        self.cardDisplayHLayout.setContentsMargins(-1, 5, -1, 5)
        self.cardDisplayHLayout.setObjectName("cardDisplayHLayout")
        self.cardDisplayTitle = QtWidgets.QLabel(self.cardHeaderDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardDisplayTitle.sizePolicy().hasHeightForWidth())
        self.cardDisplayTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cardDisplayTitle.setFont(font)
        self.cardDisplayTitle.setStyleSheet("background:none;\n"
"border:0;\n"
"border-radius:0;")
        self.cardDisplayTitle.setObjectName("cardDisplayTitle")
        self.cardDisplayHLayout.addWidget(self.cardDisplayTitle)
        self.btnCollapseDisplay = QtWidgets.QPushButton(self.cardHeaderDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCollapseDisplay.sizePolicy().hasHeightForWidth())
        self.btnCollapseDisplay.setSizePolicy(sizePolicy)
        self.btnCollapseDisplay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCollapseDisplay.setText("")
        self.btnCollapseDisplay.setObjectName("btnCollapseDisplay")
        self.cardDisplayHLayout.addWidget(self.btnCollapseDisplay)
        self.cardDisplayLayout.addWidget(self.cardHeaderDisplay)
        self.cardBodyDisplay = QtWidgets.QWidget(self.cardDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardBodyDisplay.sizePolicy().hasHeightForWidth())
        self.cardBodyDisplay.setSizePolicy(sizePolicy)
        self.cardBodyDisplay.setStyleSheet("")
        self.cardBodyDisplay.setObjectName("cardBodyDisplay")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.cardBodyDisplay)
        self.verticalLayout_14.setContentsMargins(-1, 4, -1, 6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.alignWidget1 = QtWidgets.QWidget(self.cardBodyDisplay)
        self.alignWidget1.setObjectName("alignWidget1")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.alignWidget1)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lblMaskStatic = QtWidgets.QLabel(self.alignWidget1)
        self.lblMaskStatic.setObjectName("lblMaskStatic")
        self.horizontalLayout_14.addWidget(self.lblMaskStatic)
        self.checkMaskStatic = QtWidgets.QCheckBox(self.alignWidget1)
        self.checkMaskStatic.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkMaskStatic.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkMaskStatic.setText("")
        self.checkMaskStatic.setObjectName("checkMaskStatic")
        self.horizontalLayout_14.addWidget(self.checkMaskStatic)
        self.verticalLayout_14.addWidget(self.alignWidget1)
        self.widget = QtWidgets.QWidget(self.cardBodyDisplay)
        self.widget.setObjectName("widget")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.lblKeepDuration = QtWidgets.QLabel(self.widget)
        self.lblKeepDuration.setObjectName("lblKeepDuration")
        self.horizontalLayout_18.addWidget(self.lblKeepDuration)
        self.comboKeepDuration = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboKeepDuration.sizePolicy().hasHeightForWidth())
        self.comboKeepDuration.setSizePolicy(sizePolicy)
        self.comboKeepDuration.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboKeepDuration.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.comboKeepDuration.setStyleSheet("text-align:right")
        self.comboKeepDuration.setObjectName("comboKeepDuration")
        self.horizontalLayout_18.addWidget(self.comboKeepDuration)
        self.verticalLayout_14.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.cardBodyDisplay)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.titleSignalSrc = QtWidgets.QLabel(self.widget_2)
        self.titleSignalSrc.setObjectName("titleSignalSrc")
        self.horizontalLayout_19.addWidget(self.titleSignalSrc)
        self.comboSignalsSrc = QtWidgets.QComboBox(self.widget_2)
        self.comboSignalsSrc.setObjectName("comboSignalsSrc")
        self.horizontalLayout_19.addWidget(self.comboSignalsSrc)
        self.verticalLayout_14.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.cardBodyDisplay)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btnSnap = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSnap.sizePolicy().hasHeightForWidth())
        self.btnSnap.setSizePolicy(sizePolicy)
        self.btnSnap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSnap.setObjectName("btnSnap")
        self.horizontalLayout_12.addWidget(self.btnSnap)
        self.btnSnapClear = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSnapClear.sizePolicy().hasHeightForWidth())
        self.btnSnapClear.setSizePolicy(sizePolicy)
        self.btnSnapClear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSnapClear.setObjectName("btnSnapClear")
        self.horizontalLayout_12.addWidget(self.btnSnapClear)
        self.verticalLayout_14.addWidget(self.widget_3)
        self.cardDisplayLayout.addWidget(self.cardBodyDisplay)
        self.rightMenuLayout.addWidget(self.cardDisplay)
        self.cardSession = QtWidgets.QWidget(self.rightMenu2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardSession.sizePolicy().hasHeightForWidth())
        self.cardSession.setSizePolicy(sizePolicy)
        self.cardSession.setObjectName("cardSession")
        self.cardSessionLayout = QtWidgets.QVBoxLayout(self.cardSession)
        self.cardSessionLayout.setContentsMargins(-1, 0, -1, 3)
        self.cardSessionLayout.setSpacing(0)
        self.cardSessionLayout.setObjectName("cardSessionLayout")
        self.cardHeaderSession = QtWidgets.QWidget(self.cardSession)
        self.cardHeaderSession.setObjectName("cardHeaderSession")
        self.cardSessionHeaderLayout = QtWidgets.QHBoxLayout(self.cardHeaderSession)
        self.cardSessionHeaderLayout.setContentsMargins(-1, 5, -1, 5)
        self.cardSessionHeaderLayout.setObjectName("cardSessionHeaderLayout")
        self.cardSessionTitle = QtWidgets.QLabel(self.cardHeaderSession)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cardSessionTitle.setFont(font)
        self.cardSessionTitle.setObjectName("cardSessionTitle")
        self.cardSessionHeaderLayout.addWidget(self.cardSessionTitle)
        self.btnCollapseSession = QtWidgets.QPushButton(self.cardHeaderSession)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCollapseSession.sizePolicy().hasHeightForWidth())
        self.btnCollapseSession.setSizePolicy(sizePolicy)
        self.btnCollapseSession.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCollapseSession.setText("")
        self.btnCollapseSession.setObjectName("btnCollapseSession")
        self.cardSessionHeaderLayout.addWidget(self.btnCollapseSession)
        self.cardSessionLayout.addWidget(self.cardHeaderSession)
        self.cardBodySession = QtWidgets.QWidget(self.cardSession)
        self.cardBodySession.setObjectName("cardBodySession")
        self.cardSessionBodyLayout = QtWidgets.QVBoxLayout(self.cardBodySession)
        self.cardSessionBodyLayout.setContentsMargins(0, 0, 0, -1)
        self.cardSessionBodyLayout.setObjectName("cardSessionBodyLayout")
        self.gridSessionLabels = QtWidgets.QWidget(self.cardBodySession)
        self.gridSessionLabels.setObjectName("gridSessionLabels")
        self.sessionLabelsLayout = QtWidgets.QFormLayout(self.gridSessionLabels)
        self.sessionLabelsLayout.setObjectName("sessionLabelsLayout")
        self.lblTitleSessionName = QtWidgets.QLabel(self.gridSessionLabels)
        self.lblTitleSessionName.setObjectName("lblTitleSessionName")
        self.sessionLabelsLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblTitleSessionName)
        self.lblTitleSessionFrames = QtWidgets.QLabel(self.gridSessionLabels)
        self.lblTitleSessionFrames.setObjectName("lblTitleSessionFrames")
        self.sessionLabelsLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblTitleSessionFrames)
        self.lblSessionFrames = QtWidgets.QLabel(self.gridSessionLabels)
        self.lblSessionFrames.setText("")
        self.lblSessionFrames.setObjectName("lblSessionFrames")
        self.sessionLabelsLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblSessionFrames)
        self.lblSessionName = QtWidgets.QLabel(self.gridSessionLabels)
        self.lblSessionName.setText("")
        self.lblSessionName.setObjectName("lblSessionName")
        self.sessionLabelsLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lblSessionName)
        self.cardSessionBodyLayout.addWidget(self.gridSessionLabels)
        self.gridSessionButtons = QtWidgets.QWidget(self.cardBodySession)
        self.gridSessionButtons.setObjectName("gridSessionButtons")
        self.sessionButtonsLayout = QtWidgets.QGridLayout(self.gridSessionButtons)
        self.sessionButtonsLayout.setContentsMargins(9, 0, 9, 0)
        self.sessionButtonsLayout.setObjectName("sessionButtonsLayout")
        self.btnSessionLoad = QtWidgets.QPushButton(self.gridSessionButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSessionLoad.sizePolicy().hasHeightForWidth())
        self.btnSessionLoad.setSizePolicy(sizePolicy)
        self.btnSessionLoad.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSessionLoad.setObjectName("btnSessionLoad")
        self.sessionButtonsLayout.addWidget(self.btnSessionLoad, 3, 2, 1, 1)
        self.btnSessionRec = QtWidgets.QPushButton(self.gridSessionButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSessionRec.sizePolicy().hasHeightForWidth())
        self.btnSessionRec.setSizePolicy(sizePolicy)
        self.btnSessionRec.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSessionRec.setObjectName("btnSessionRec")
        self.sessionButtonsLayout.addWidget(self.btnSessionRec, 0, 2, 1, 1)
        self.btnSessionLive = QtWidgets.QPushButton(self.gridSessionButtons)
        self.btnSessionLive.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSessionLive.setObjectName("btnSessionLive")
        self.sessionButtonsLayout.addWidget(self.btnSessionLive, 0, 0, 1, 1)
        self.btnSessionSave = QtWidgets.QPushButton(self.gridSessionButtons)
        self.btnSessionSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSessionSave.setObjectName("btnSessionSave")
        self.sessionButtonsLayout.addWidget(self.btnSessionSave, 3, 0, 1, 1)
        self.btnSessionPause = QtWidgets.QPushButton(self.gridSessionButtons)
        self.btnSessionPause.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSessionPause.setObjectName("btnSessionPause")
        self.sessionButtonsLayout.addWidget(self.btnSessionPause, 1, 0, 1, 1)
        self.btnSessionReplay = QtWidgets.QPushButton(self.gridSessionButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSessionReplay.sizePolicy().hasHeightForWidth())
        self.btnSessionReplay.setSizePolicy(sizePolicy)
        self.btnSessionReplay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSessionReplay.setObjectName("btnSessionReplay")
        self.sessionButtonsLayout.addWidget(self.btnSessionReplay, 1, 2, 1, 1)
        self.btnSessionForensic = QtWidgets.QPushButton(self.gridSessionButtons)
        self.btnSessionForensic.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSessionForensic.setObjectName("btnSessionForensic")
        self.sessionButtonsLayout.addWidget(self.btnSessionForensic, 2, 0, 1, 1)
        self.btnSessionNew = QtWidgets.QPushButton(self.gridSessionButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSessionNew.sizePolicy().hasHeightForWidth())
        self.btnSessionNew.setSizePolicy(sizePolicy)
        self.btnSessionNew.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSessionNew.setObjectName("btnSessionNew")
        self.sessionButtonsLayout.addWidget(self.btnSessionNew, 2, 2, 1, 1)
        self.cardSessionBodyLayout.addWidget(self.gridSessionButtons)
        self.cardSessionLayout.addWidget(self.cardBodySession)
        self.rightMenuLayout.addWidget(self.cardSession)
        self.cardFilter = QtWidgets.QWidget(self.rightMenu2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardFilter.sizePolicy().hasHeightForWidth())
        self.cardFilter.setSizePolicy(sizePolicy)
        self.cardFilter.setObjectName("cardFilter")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.cardFilter)
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.cardHeaderFilter = QtWidgets.QWidget(self.cardFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardHeaderFilter.sizePolicy().hasHeightForWidth())
        self.cardHeaderFilter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cardHeaderFilter.setFont(font)
        self.cardHeaderFilter.setStyleSheet("")
        self.cardHeaderFilter.setObjectName("cardHeaderFilter")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.cardHeaderFilter)
        self.horizontalLayout_13.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.cardFilterTitle = QtWidgets.QLabel(self.cardHeaderFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardFilterTitle.sizePolicy().hasHeightForWidth())
        self.cardFilterTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cardFilterTitle.setFont(font)
        self.cardFilterTitle.setStyleSheet("background:none;\n"
"border:0;\n"
"border-radius:0;")
        self.cardFilterTitle.setObjectName("cardFilterTitle")
        self.horizontalLayout_13.addWidget(self.cardFilterTitle)
        self.btnCollapseFilter = QtWidgets.QPushButton(self.cardHeaderFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCollapseFilter.sizePolicy().hasHeightForWidth())
        self.btnCollapseFilter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnCollapseFilter.setFont(font)
        self.btnCollapseFilter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCollapseFilter.setText("")
        self.btnCollapseFilter.setObjectName("btnCollapseFilter")
        self.horizontalLayout_13.addWidget(self.btnCollapseFilter)
        self.verticalLayout_11.addWidget(self.cardHeaderFilter)
        self.cardBodyFilter = QtWidgets.QWidget(self.cardFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardBodyFilter.sizePolicy().hasHeightForWidth())
        self.cardBodyFilter.setSizePolicy(sizePolicy)
        self.cardBodyFilter.setMinimumSize(QtCore.QSize(0, 0))
        self.cardBodyFilter.setStyleSheet("")
        self.cardBodyFilter.setObjectName("cardBodyFilter")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.cardBodyFilter)
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.idFilter = QtWidgets.QTreeWidget(self.cardBodyFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idFilter.sizePolicy().hasHeightForWidth())
        self.idFilter.setSizePolicy(sizePolicy)
        self.idFilter.setColumnCount(1)
        self.idFilter.setObjectName("idFilter")
        self.verticalLayout_12.addWidget(self.idFilter)
        self.verticalLayout_11.addWidget(self.cardBodyFilter)
        self.rightMenuLayout.addWidget(self.cardFilter)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.rightMenuLayout.addItem(spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.rightMenuLayout.addItem(spacerItem13)
        self.rightMenu.setWidget(self.rightMenu2)
        self.horizontalLayout_11.addWidget(self.rightMenu)
        self.verticalLayout_13.addWidget(self.body)
        self.stackedWidget.addWidget(self.analysisPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.loginLogo, self.fldUsername)
        MainWindow.setTabOrder(self.fldUsername, self.fldProfileName)
        MainWindow.setTabOrder(self.fldProfileName, self.fldPassword)
        MainWindow.setTabOrder(self.fldPassword, self.fldConfirmPassword)
        MainWindow.setTabOrder(self.fldConfirmPassword, self.btnLogin)
        MainWindow.setTabOrder(self.btnLogin, self.btnMainMenu)
        MainWindow.setTabOrder(self.btnMainMenu, self.btnAnalysis)
        MainWindow.setTabOrder(self.btnAnalysis, self.btnDevices)
        MainWindow.setTabOrder(self.btnDevices, self.btnServer)
        MainWindow.setTabOrder(self.btnServer, self.btnNotification)
        MainWindow.setTabOrder(self.btnNotification, self.btnConfig)
        MainWindow.setTabOrder(self.btnConfig, self.btnProfile)
        MainWindow.setTabOrder(self.btnProfile, self.btnNewAnalysis)
        MainWindow.setTabOrder(self.btnNewAnalysis, self.btnLoadAnalysis)
        MainWindow.setTabOrder(self.btnLoadAnalysis, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.btnEditVehicle)
        MainWindow.setTabOrder(self.btnEditVehicle, self.btnBusCan)
        MainWindow.setTabOrder(self.btnBusCan, self.btnBusLin)
        MainWindow.setTabOrder(self.btnBusLin, self.btnBusKln)
        MainWindow.setTabOrder(self.btnBusKln, self.btnCmdEditor)
        MainWindow.setTabOrder(self.btnCmdEditor, self.btnShowRightMenu)
        MainWindow.setTabOrder(self.btnShowRightMenu, self.btnCollapseDisplay)
        MainWindow.setTabOrder(self.btnCollapseDisplay, self.btnCollapseSession)
        MainWindow.setTabOrder(self.btnCollapseSession, self.btnSessionLive)
        MainWindow.setTabOrder(self.btnSessionLive, self.btnSessionRec)
        MainWindow.setTabOrder(self.btnSessionRec, self.btnSessionPause)
        MainWindow.setTabOrder(self.btnSessionPause, self.btnSessionReplay)
        MainWindow.setTabOrder(self.btnSessionReplay, self.btnSessionForensic)
        MainWindow.setTabOrder(self.btnSessionForensic, self.btnSessionNew)
        MainWindow.setTabOrder(self.btnSessionNew, self.btnSessionSave)
        MainWindow.setTabOrder(self.btnSessionSave, self.btnSessionLoad)
        MainWindow.setTabOrder(self.btnSessionLoad, self.btnCollapseFilter)
        MainWindow.setTabOrder(self.btnCollapseFilter, self.idFilter)
        MainWindow.setTabOrder(self.idFilter, self.msgTable)
        MainWindow.setTabOrder(self.msgTable, self.rightMenu)
        MainWindow.setTabOrder(self.rightMenu, self.stat)
        MainWindow.setTabOrder(self.stat, self.srv)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Share-CAN"))
        self.mainMenu.setProperty("cssClass", _translate("MainWindow", "mainMenu"))
        self.btnMainMenu.setProperty("cssClass", _translate("MainWindow", "menuBtnMain"))
        self.label.setText(_translate("MainWindow", "APP_NAME"))
        self.label.setProperty("cssClass", _translate("MainWindow", "appTitle"))
        self.btnAnalysis.setProperty("cssClass", _translate("MainWindow", "menuBtn"))
        self.btnDevices.setProperty("cssClass", _translate("MainWindow", "menuBtn"))
        self.btnServer.setProperty("cssClass", _translate("MainWindow", "menuBtn"))
        self.btnNotification.setProperty("cssClass", _translate("MainWindow", "menuBtn"))
        self.btnConfig.setProperty("cssClass", _translate("MainWindow", "menuBtn"))
        self.btnProfile.setProperty("cssClass", _translate("MainWindow", "menuBtn"))
        self.loginCard.setProperty("cssClass", _translate("MainWindow", "cardBordered"))
        self.loginCardHeader.setProperty("cssClass", _translate("MainWindow", "cardHeader"))
        self.loginTitle.setText(_translate("MainWindow", "LOGIN_TITLE"))
        self.loginTitle.setProperty("cssClass", _translate("MainWindow", "cardTitle"))
        self.loginLogoSpacer.setProperty("cssClass", _translate("MainWindow", "cardLogo"))
        self.loginLogo.setProperty("cssClass", _translate("MainWindow", "btnLogo"))
        self.loginBody.setProperty("cssClass", _translate("MainWindow", "cardBody"))
        self.labelUsername.setText(_translate("MainWindow", "USERNAME"))
        self.labelPassword.setText(_translate("MainWindow", "PASSWORD"))
        self.btnLogin.setText(_translate("MainWindow", "LOGIN_BTN"))
        self.btnLogin.setProperty("cssClass", _translate("MainWindow", "btn-primary"))
        self.errorMsg.setText(_translate("MainWindow", "ERROR_MSG"))
        self.errorMsg.setProperty("cssClass", _translate("MainWindow", "text-danger"))
        self.newUserMsg.setText(_translate("MainWindow", "NEW_USER_PROMPT"))
        self.labelProfileName.setText(_translate("MainWindow", "PROFILE_NAME"))
        self.btnNewAnalysis.setText(_translate("MainWindow", "NEW_ANALYSIS"))
        self.btnNewAnalysis.setProperty("cssClass", _translate("MainWindow", "btn-primary"))
        self.btnLoadAnalysis.setText(_translate("MainWindow", "LOAD_ANALYSIS"))
        self.btnLoadAnalysis.setProperty("cssClass", _translate("MainWindow", "btn-primary"))
        self.cardAnalysis.setProperty("cssClass", _translate("MainWindow", "card"))
        self.cardTitleAnalysis.setProperty("cssClass", _translate("MainWindow", "cardHeader"))
        self.titleAnalysis.setText(_translate("MainWindow", "LAST_ANALYSIS"))
        self.cardBodyAnalysis.setProperty("cssClass", _translate("MainWindow", "cardBody"))
        self.lastAnalysisModelTitle.setText(_translate("MainWindow", "ANALYSIS_TYPE"))
        self.lastAnalysisPrivacyTitle.setText(_translate("MainWindow", "ANALYSIS_PRIVACY"))
        self.lastAnalysisDateTitle.setText(_translate("MainWindow", "ANALYSIS_DATE"))
        self.lastAnalysisIconTitle.setText(_translate("MainWindow", "ANALYSIS_MODEL"))
        self.cardTitleStat.setProperty("cssClass", _translate("MainWindow", "cardHeader"))
        self.titleStat.setText(_translate("MainWindow", "STATS"))
        self.cardBodyStat.setProperty("cssClass", _translate("MainWindow", "cardBody"))
        self.pushButton_4.setText(_translate("MainWindow", "SOFT_UPDATE"))
        self.cardServer.setProperty("cssClass", _translate("MainWindow", "card"))
        self.cardTitleServer.setProperty("cssClass", _translate("MainWindow", "cardHeader"))
        self.label_2.setText(_translate("MainWindow", "SERVER"))
        self.cardBodyServer.setProperty("cssClass", _translate("MainWindow", "cardBody"))
        self.pushButton_3.setText(_translate("MainWindow", "SRV_UPDATE"))
        self.vehicleTitle.setText(_translate("MainWindow", "Ford Focus - <b>2017</b> - WWFG1345FEM"))
        self.btnEditVehicle.setToolTip(_translate("MainWindow", "EDIT_ANALYSIS_TOOLTIP"))
        self.btnEditVehicle.setProperty("cssClass", _translate("MainWindow", "btn-primary"))
        self.btnBusCan.setText(_translate("MainWindow", "CAN_BTN"))
        self.btnBusCan.setProperty("cssClass", _translate("MainWindow", "btn-secondary"))
        self.btnBusLin.setText(_translate("MainWindow", "LIN_BTN"))
        self.btnBusLin.setProperty("cssClass", _translate("MainWindow", "btn-disabled"))
        self.btnBusKln.setText(_translate("MainWindow", "KLN_BTN"))
        self.btnBusKln.setProperty("cssClass", _translate("MainWindow", "btn-disabled"))
        self.btnMap.setText(_translate("MainWindow", "ECU_MAP_SCAN_UDS"))
        self.btnMap.setProperty("cssClass", _translate("MainWindow", "btn-secondary"))
        self.btnCmdEditor.setText(_translate("MainWindow", "CMD_EDITOR"))
        self.btnCmdEditor.setProperty("cssClass", _translate("MainWindow", "btn-secondary"))
        self.btnNotes.setText(_translate("MainWindow", "NOTES"))
        self.btnNotes.setProperty("cssClass", _translate("MainWindow", "btn-secondary"))
        self.btnShowRightMenu.setText(_translate("MainWindow", "HIDE_MENU"))
        self.btnShowRightMenu.setProperty("cssClass", _translate("MainWindow", "btn-secondary"))
        self.cardDisplay.setProperty("cssClass", _translate("MainWindow", "card"))
        self.cardHeaderDisplay.setProperty("cssClass", _translate("MainWindow", "cardHeader"))
        self.cardDisplayTitle.setText(_translate("MainWindow", "DISPLAY"))
        self.cardDisplayTitle.setProperty("cssClass", _translate("MainWindow", "cardTitle"))
        self.btnCollapseDisplay.setToolTip(_translate("MainWindow", "TOGGLE_TOOLTIP"))
        self.cardBodyDisplay.setProperty("cssClass", _translate("MainWindow", "cardBody"))
        self.lblMaskStatic.setText(_translate("MainWindow", "MASK_STATIC"))
        self.lblKeepDuration.setText(_translate("MainWindow", "KEEP_DURATION"))
        self.titleSignalSrc.setText(_translate("MainWindow", "SIGNAL_SRC"))
        self.btnSnap.setToolTip(_translate("MainWindow", "SNAP_ID_TOOLTIP"))
        self.btnSnap.setText(_translate("MainWindow", "SNAP_ID"))
        self.btnSnap.setProperty("cssClass", _translate("MainWindow", "btn-primary"))
        self.btnSnapClear.setToolTip(_translate("MainWindow", "CLEAR_SNAP_TOOLTIP"))
        self.btnSnapClear.setText(_translate("MainWindow", "CLEAR_SNAP"))
        self.btnSnapClear.setProperty("cssClass", _translate("MainWindow", "btn-primary"))
        self.cardSession.setProperty("cssClass", _translate("MainWindow", "card"))
        self.cardHeaderSession.setProperty("cssClass", _translate("MainWindow", "cardHeader"))
        self.cardSessionTitle.setText(_translate("MainWindow", "SESSION"))
        self.btnCollapseSession.setToolTip(_translate("MainWindow", "TOGGLE_TOOLTIP"))
        self.cardBodySession.setProperty("cssClass", _translate("MainWindow", "cardBody"))
        self.lblTitleSessionName.setText(_translate("MainWindow", "SESSION_NAME"))
        self.lblTitleSessionFrames.setText(_translate("MainWindow", "SESSION_FRAMES"))
        self.btnSessionLoad.setToolTip(_translate("MainWindow", "SESSION_LOAD_TOOLTIP"))
        self.btnSessionLoad.setText(_translate("MainWindow", "LOAD"))
        self.btnSessionLoad.setProperty("cssClass", _translate("MainWindow", "btn-primary"))
        self.btnSessionRec.setToolTip(_translate("MainWindow", "SESSION_REPLAY_TOOLTIP"))
        self.btnSessionRec.setText(_translate("MainWindow", "REC"))
        self.btnSessionRec.setProperty("cssClass", _translate("MainWindow", "btn-primary"))
        self.btnSessionLive.setToolTip(_translate("MainWindow", "SESSION_LIVE_TOOLTIP"))
        self.btnSessionLive.setText(_translate("MainWindow", "LIVE"))
        self.btnSessionLive.setProperty("cssClass", _translate("MainWindow", "btn-primary"))
        self.btnSessionSave.setToolTip(_translate("MainWindow", "SESSION_SAVE_TOOLTIP"))
        self.btnSessionSave.setText(_translate("MainWindow", "SAVE"))
        self.btnSessionSave.setProperty("cssClass", _translate("MainWindow", "btn-primary"))
        self.btnSessionPause.setToolTip(_translate("MainWindow", "SESSION_PAUSE_TOOLTIP"))
        self.btnSessionPause.setText(_translate("MainWindow", "PAUSE"))
        self.btnSessionPause.setProperty("cssClass", _translate("MainWindow", "btn-primary"))
        self.btnSessionReplay.setToolTip(_translate("MainWindow", "SESSION_REPLAY_TOOLTIP"))
        self.btnSessionReplay.setText(_translate("MainWindow", "REPLAY"))
        self.btnSessionReplay.setProperty("cssClass", _translate("MainWindow", "btn-primary"))
        self.btnSessionForensic.setToolTip(_translate("MainWindow", "SESSION_FORENSIC_TOOLTIP"))
        self.btnSessionForensic.setText(_translate("MainWindow", "FORENSIC"))
        self.btnSessionForensic.setProperty("cssClass", _translate("MainWindow", "btn-primary"))
        self.btnSessionNew.setToolTip(_translate("MainWindow", "SESSION_NEW_TOOLTIP"))
        self.btnSessionNew.setText(_translate("MainWindow", "NEW"))
        self.btnSessionNew.setProperty("cssClass", _translate("MainWindow", "btn-primary"))
        self.cardFilter.setProperty("cssClass", _translate("MainWindow", "card"))
        self.cardHeaderFilter.setProperty("cssClass", _translate("MainWindow", "cardHeader"))
        self.cardFilterTitle.setText(_translate("MainWindow", "FILTERS"))
        self.cardFilterTitle.setProperty("cssClass", _translate("MainWindow", "cardTitle"))
        self.btnCollapseFilter.setToolTip(_translate("MainWindow", "TOGGLE_TOOLTIP"))
        self.cardBodyFilter.setProperty("cssClass", _translate("MainWindow", "cardBody"))
        self.idFilter.setSortingEnabled(True)
        self.idFilter.headerItem().setText(0, _translate("MainWindow", "BUS - ID"))

from modules.FrameWindow import TableView
