# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form-map.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MAP(object):
    def setupUi(self, MAP):
        MAP.setObjectName("MAP")
        MAP.resize(993, 568)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MAP.sizePolicy().hasHeightForWidth())
        MAP.setSizePolicy(sizePolicy)
        MAP.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(MAP)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(MAP)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setObjectName("tabWidget")
        self.tabMap = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabMap.sizePolicy().hasHeightForWidth())
        self.tabMap.setSizePolicy(sizePolicy)
        self.tabMap.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabMap.setStyleSheet("")
        self.tabMap.setObjectName("tabMap")
        self.gridLayout = QtWidgets.QGridLayout(self.tabMap)
        self.gridLayout.setObjectName("gridLayout")
        self.lblSrc = QtWidgets.QLabel(self.tabMap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSrc.sizePolicy().hasHeightForWidth())
        self.lblSrc.setSizePolicy(sizePolicy)
        self.lblSrc.setObjectName("lblSrc")
        self.gridLayout.addWidget(self.lblSrc, 0, 0, 1, 1)
        self.lblBlank = QtWidgets.QLabel(self.tabMap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBlank.sizePolicy().hasHeightForWidth())
        self.lblBlank.setSizePolicy(sizePolicy)
        self.lblBlank.setText("")
        self.lblBlank.setObjectName("lblBlank")
        self.gridLayout.addWidget(self.lblBlank, 0, 2, 1, 1)
        self.comboSrc = QtWidgets.QComboBox(self.tabMap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboSrc.sizePolicy().hasHeightForWidth())
        self.comboSrc.setSizePolicy(sizePolicy)
        self.comboSrc.setMinimumSize(QtCore.QSize(120, 0))
        self.comboSrc.setObjectName("comboSrc")
        self.comboSrc.addItem("")
        self.comboSrc.addItem("")
        self.comboSrc.addItem("")
        self.comboSrc.addItem("")
        self.gridLayout.addWidget(self.comboSrc, 0, 1, 1, 1)
        self.btnApply = QtWidgets.QPushButton(self.tabMap)
        self.btnApply.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnApply.setObjectName("btnApply")
        self.gridLayout.addWidget(self.btnApply, 0, 3, 1, 1)
        self.listMap = QtWidgets.QListView(self.tabMap)
        self.listMap.setObjectName("listMap")
        self.gridLayout.addWidget(self.listMap, 1, 0, 1, 4)
        self.tabWidget.addTab(self.tabMap, "")
        self.tabScan = QtWidgets.QWidget()
        self.tabScan.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabScan.setObjectName("tabScan")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabScan)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.busList = QtWidgets.QWidget(self.tabScan)
        self.busList.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.busList.sizePolicy().hasHeightForWidth())
        self.busList.setSizePolicy(sizePolicy)
        self.busList.setObjectName("busList")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.busList)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scanOpt = QtWidgets.QWidget(self.busList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scanOpt.sizePolicy().hasHeightForWidth())
        self.scanOpt.setSizePolicy(sizePolicy)
        self.scanOpt.setObjectName("scanOpt")
        self.formLayout = QtWidgets.QFormLayout(self.scanOpt)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.scanOpt)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBus = QtWidgets.QComboBox(self.scanOpt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBus.sizePolicy().hasHeightForWidth())
        self.comboBus.setSizePolicy(sizePolicy)
        self.comboBus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBus.setObjectName("comboBus")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBus)
        self.label_2 = QtWidgets.QLabel(self.scanOpt)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboDevice = QtWidgets.QComboBox(self.scanOpt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboDevice.sizePolicy().hasHeightForWidth())
        self.comboDevice.setSizePolicy(sizePolicy)
        self.comboDevice.setMinimumSize(QtCore.QSize(250, 0))
        self.comboDevice.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboDevice.setObjectName("comboDevice")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboDevice)
        self.label_3 = QtWidgets.QLabel(self.scanOpt)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.fldStart = QtWidgets.QLineEdit(self.scanOpt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldStart.sizePolicy().hasHeightForWidth())
        self.fldStart.setSizePolicy(sizePolicy)
        self.fldStart.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fldStart.setMaxLength(8)
        self.fldStart.setObjectName("fldStart")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fldStart)
        self.label_4 = QtWidgets.QLabel(self.scanOpt)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.fldEnd = QtWidgets.QLineEdit(self.scanOpt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldEnd.sizePolicy().hasHeightForWidth())
        self.fldEnd.setSizePolicy(sizePolicy)
        self.fldEnd.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fldEnd.setMaxLength(8)
        self.fldEnd.setObjectName("fldEnd")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fldEnd)
        self.label_5 = QtWidgets.QLabel(self.scanOpt)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboMode = QtWidgets.QComboBox(self.scanOpt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboMode.sizePolicy().hasHeightForWidth())
        self.comboMode.setSizePolicy(sizePolicy)
        self.comboMode.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboMode.setObjectName("comboMode")
        self.comboMode.addItem("")
        self.comboMode.addItem("")
        self.comboMode.addItem("")
        self.comboMode.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboMode)
        self.label_6 = QtWidgets.QLabel(self.scanOpt)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.checkSession = QtWidgets.QCheckBox(self.scanOpt)
        self.checkSession.setEnabled(False)
        self.checkSession.setChecked(True)
        self.checkSession.setObjectName("checkSession")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.checkSession)
        self.checkTester = QtWidgets.QCheckBox(self.scanOpt)
        self.checkTester.setChecked(False)
        self.checkTester.setObjectName("checkTester")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.checkTester)
        self.checkReset = QtWidgets.QCheckBox(self.scanOpt)
        self.checkReset.setObjectName("checkReset")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.checkReset)
        self.checkSecurity = QtWidgets.QCheckBox(self.scanOpt)
        self.checkSecurity.setObjectName("checkSecurity")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.checkSecurity)
        self.checkRoutine = QtWidgets.QCheckBox(self.scanOpt)
        self.checkRoutine.setObjectName("checkRoutine")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.checkRoutine)
        self.checkRead = QtWidgets.QCheckBox(self.scanOpt)
        self.checkRead.setObjectName("checkRead")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.checkRead)
        self.checkRequest = QtWidgets.QCheckBox(self.scanOpt)
        self.checkRequest.setObjectName("checkRequest")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.checkRequest)
        self.checkOBD2 = QtWidgets.QCheckBox(self.scanOpt)
        self.checkOBD2.setObjectName("checkOBD2")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.checkOBD2)
        self.widget_3 = QtWidgets.QWidget(self.scanOpt)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnScan = QtWidgets.QPushButton(self.widget_3)
        self.btnScan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnScan.setObjectName("btnScan")
        self.horizontalLayout_3.addWidget(self.btnScan)
        self.btnStop = QtWidgets.QPushButton(self.widget_3)
        self.btnStop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_3.addWidget(self.btnStop)
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.widget_3)
        self.label_7 = QtWidgets.QLabel(self.scanOpt)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.comboFeedback = QtWidgets.QComboBox(self.scanOpt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboFeedback.sizePolicy().hasHeightForWidth())
        self.comboFeedback.setSizePolicy(sizePolicy)
        self.comboFeedback.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.comboFeedback.setObjectName("comboFeedback")
        self.comboFeedback.addItem("")
        self.comboFeedback.addItem("")
        self.comboFeedback.addItem("")
        self.comboFeedback.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboFeedback)
        self.label_8 = QtWidgets.QLabel(self.scanOpt)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.fldPadding = QtWidgets.QLineEdit(self.scanOpt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldPadding.sizePolicy().hasHeightForWidth())
        self.fldPadding.setSizePolicy(sizePolicy)
        self.fldPadding.setMinimumSize(QtCore.QSize(0, 0))
        self.fldPadding.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fldPadding.setMaxLength(2)
        self.fldPadding.setObjectName("fldPadding")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fldPadding)
        self.horizontalLayout.addWidget(self.scanOpt)
        self.widget = QtWidgets.QWidget(self.busList)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listResults = QtWidgets.QTreeView(self.widget)
        self.listResults.setObjectName("listResults")
        self.verticalLayout_3.addWidget(self.listResults)
        self.errorMsg = QtWidgets.QLabel(self.widget)
        self.errorMsg.setText("")
        self.errorMsg.setObjectName("errorMsg")
        self.verticalLayout_3.addWidget(self.errorMsg)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progress = QtWidgets.QProgressBar(self.widget_2)
        self.progress.setProperty("value", 24)
        self.progress.setObjectName("progress")
        self.horizontalLayout_2.addWidget(self.progress)
        self.btnSave = QtWidgets.QPushButton(self.widget_2)
        self.btnSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_2.addWidget(self.btnSave)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.busList)
        self.tabWidget.addTab(self.tabScan, "")
        self.verticalLayout.addWidget(self.tabWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(MAP)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MAP)

    def retranslateUi(self, MAP):
        _translate = QtCore.QCoreApplication.translate
        self.lblSrc.setText(_translate("MAP", "SRC"))
        self.comboSrc.setItemText(0, _translate("MAP", "ANALYSIS"))
        self.comboSrc.setItemText(1, _translate("MAP", "ENGINE_CODE"))
        self.comboSrc.setItemText(2, _translate("MAP", "MODEL"))
        self.comboSrc.setItemText(3, _translate("MAP", "MANUFACTURER"))
        self.btnApply.setText(_translate("MAP", "APPLY_CHANGES"))
        self.btnApply.setProperty("cssClass", _translate("MAP", "btn-success"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMap), _translate("MAP", "ECU"))
        self.label.setText(_translate("MAP", "BUS"))
        self.label_2.setText(_translate("MAP", "DEVICE"))
        self.label_3.setText(_translate("MAP", "START"))
        self.fldStart.setText(_translate("MAP", "700"))
        self.label_4.setText(_translate("MAP", "END"))
        self.fldEnd.setText(_translate("MAP", "7F7"))
        self.label_5.setText(_translate("MAP", "MODE"))
        self.comboMode.setItemText(0, _translate("MAP", "QUICK"))
        self.comboMode.setItemText(1, _translate("MAP", "LEGACY"))
        self.comboMode.setItemText(2, _translate("MAP", "SMART_QUICK"))
        self.comboMode.setItemText(3, _translate("MAP", "SMART"))
        self.label_6.setText(_translate("MAP", "SERVICES"))
        self.checkSession.setText(_translate("MAP", "SESSION"))
        self.checkTester.setText(_translate("MAP", "TESTER_PRESENT"))
        self.checkReset.setText(_translate("MAP", "RESET"))
        self.checkSecurity.setText(_translate("MAP", "SECURITY"))
        self.checkRoutine.setText(_translate("MAP", "ROUTINE_CONTROL"))
        self.checkRead.setText(_translate("MAP", "READ_MEMORY_BY"))
        self.checkRequest.setText(_translate("MAP", "REQUEST_UPLOAD_DOWNLOAD"))
        self.checkOBD2.setText(_translate("MAP", "OBD2_REQUESTS"))
        self.btnScan.setText(_translate("MAP", "SCAN"))
        self.btnScan.setProperty("cssClass", _translate("MAP", "btn-success"))
        self.btnStop.setText(_translate("MAP", "STOP"))
        self.btnStop.setProperty("cssClass", _translate("MAP", "btn-danger"))
        self.label_7.setText(_translate("MAP", "FEEDBACK"))
        self.comboFeedback.setItemText(0, _translate("MAP", "NONE"))
        self.comboFeedback.setItemText(1, _translate("MAP", "FEEDBACK_LIVE"))
        self.comboFeedback.setItemText(2, _translate("MAP", "FEEDBACK_RECORD"))
        self.comboFeedback.setItemText(3, _translate("MAP", "FEEDBACK_RECORD_NEW"))
        self.label_8.setText(_translate("MAP", "PADDING"))
        self.errorMsg.setProperty("cssClass", _translate("MAP", "text-danger"))
        self.btnSave.setText(_translate("MAP", "SAVE"))
        self.btnSave.setProperty("cssClass", _translate("MAP", "btn-success"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabScan), _translate("MAP", "UDS_SCANNER"))

