# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form-replay.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_REPLAY(object):
    def setupUi(self, REPLAY):
        REPLAY.setObjectName("REPLAY")
        REPLAY.resize(600, 310)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(REPLAY.sizePolicy().hasHeightForWidth())
        REPLAY.setSizePolicy(sizePolicy)
        REPLAY.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(REPLAY)
        self.verticalLayout.setObjectName("verticalLayout")
        self.replayMainGrid = QtWidgets.QWidget(REPLAY)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replayMainGrid.sizePolicy().hasHeightForWidth())
        self.replayMainGrid.setSizePolicy(sizePolicy)
        self.replayMainGrid.setObjectName("replayMainGrid")
        self.formLayout = QtWidgets.QFormLayout(self.replayMainGrid)
        self.formLayout.setContentsMargins(0, 0, 0, 6)
        self.formLayout.setObjectName("formLayout")
        self.titleFrames = QtWidgets.QLabel(self.replayMainGrid)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.titleFrames.setFont(font)
        self.titleFrames.setObjectName("titleFrames")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.titleFrames)
        self.titleLoop = QtWidgets.QLabel(self.replayMainGrid)
        self.titleLoop.setObjectName("titleLoop")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.titleLoop)
        self.lblFrames = QtWidgets.QLabel(self.replayMainGrid)
        self.lblFrames.setText("")
        self.lblFrames.setObjectName("lblFrames")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblFrames)
        self.checkLoop = QtWidgets.QCheckBox(self.replayMainGrid)
        self.checkLoop.setText("")
        self.checkLoop.setObjectName("checkLoop")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkLoop)
        self.titleMode = QtWidgets.QLabel(self.replayMainGrid)
        self.titleMode.setObjectName("titleMode")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.titleMode)
        self.lblMode = QtWidgets.QLabel(self.replayMainGrid)
        self.lblMode.setText("")
        self.lblMode.setObjectName("lblMode")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lblMode)
        self.label = QtWidgets.QLabel(self.replayMainGrid)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.verticalLayout.addWidget(self.replayMainGrid)
        self.splitRequired = QtWidgets.QFrame(REPLAY)
        self.splitRequired.setFrameShape(QtWidgets.QFrame.HLine)
        self.splitRequired.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitRequired.setObjectName("splitRequired")
        self.verticalLayout.addWidget(self.splitRequired)
        self.deviceTitle = QtWidgets.QLabel(REPLAY)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deviceTitle.sizePolicy().hasHeightForWidth())
        self.deviceTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.deviceTitle.setFont(font)
        self.deviceTitle.setObjectName("deviceTitle")
        self.verticalLayout.addWidget(self.deviceTitle)
        self.replayBusGridWidget = QtWidgets.QWidget(REPLAY)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replayBusGridWidget.sizePolicy().hasHeightForWidth())
        self.replayBusGridWidget.setSizePolicy(sizePolicy)
        self.replayBusGridWidget.setObjectName("replayBusGridWidget")
        self.replayBusGridLayout = QtWidgets.QGridLayout(self.replayBusGridWidget)
        self.replayBusGridLayout.setObjectName("replayBusGridLayout")
        self.titleType = QtWidgets.QLabel(self.replayBusGridWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleType.setFont(font)
        self.titleType.setObjectName("titleType")
        self.replayBusGridLayout.addWidget(self.titleType, 0, 0, 1, 1)
        self.titleIface = QtWidgets.QLabel(self.replayBusGridWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleIface.setFont(font)
        self.titleIface.setObjectName("titleIface")
        self.replayBusGridLayout.addWidget(self.titleIface, 0, 2, 1, 1)
        self.titleBus = QtWidgets.QLabel(self.replayBusGridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleBus.sizePolicy().hasHeightForWidth())
        self.titleBus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleBus.setFont(font)
        self.titleBus.setObjectName("titleBus")
        self.replayBusGridLayout.addWidget(self.titleBus, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.replayBusGridWidget)
        self.split = QtWidgets.QFrame(REPLAY)
        self.split.setFrameShape(QtWidgets.QFrame.HLine)
        self.split.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.split.setObjectName("split")
        self.verticalLayout.addWidget(self.split)
        self.replayBtnGrid = QtWidgets.QWidget(REPLAY)
        self.replayBtnGrid.setObjectName("replayBtnGrid")
        self.gridLayout = QtWidgets.QGridLayout(self.replayBtnGrid)
        self.gridLayout.setContentsMargins(0, -1, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.btnSmartReplay = QtWidgets.QPushButton(self.replayBtnGrid)
        self.btnSmartReplay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSmartReplay.setObjectName("btnSmartReplay")
        self.gridLayout.addWidget(self.btnSmartReplay, 4, 1, 1, 1)
        self.btnRevert = QtWidgets.QPushButton(self.replayBtnGrid)
        self.btnRevert.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRevert.setObjectName("btnRevert")
        self.gridLayout.addWidget(self.btnRevert, 2, 1, 1, 1)
        self.btnAddCommand = QtWidgets.QPushButton(self.replayBtnGrid)
        self.btnAddCommand.setObjectName("btnAddCommand")
        self.gridLayout.addWidget(self.btnAddCommand, 4, 2, 1, 1)
        self.progress = QtWidgets.QProgressBar(self.replayBtnGrid)
        self.progress.setProperty("value", 0)
        self.progress.setObjectName("progress")
        self.gridLayout.addWidget(self.progress, 0, 0, 1, 4)
        self.btnSlice = QtWidgets.QPushButton(self.replayBtnGrid)
        self.btnSlice.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSlice.setObjectName("btnSlice")
        self.gridLayout.addWidget(self.btnSlice, 2, 2, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(self.replayBtnGrid)
        self.btnCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout.addWidget(self.btnCancel, 3, 3, 1, 1)
        self.btnUpdateSession = QtWidgets.QPushButton(self.replayBtnGrid)
        self.btnUpdateSession.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnUpdateSession.setObjectName("btnUpdateSession")
        self.gridLayout.addWidget(self.btnUpdateSession, 4, 3, 1, 1)
        self.btnReplayAll = QtWidgets.QPushButton(self.replayBtnGrid)
        self.btnReplayAll.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnReplayAll.setObjectName("btnReplayAll")
        self.gridLayout.addWidget(self.btnReplayAll, 4, 0, 1, 1)
        self.btnNext = QtWidgets.QPushButton(self.replayBtnGrid)
        self.btnNext.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNext.setObjectName("btnNext")
        self.gridLayout.addWidget(self.btnNext, 2, 3, 1, 1)
        self.btnPrevious = QtWidgets.QPushButton(self.replayBtnGrid)
        self.btnPrevious.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPrevious.setObjectName("btnPrevious")
        self.gridLayout.addWidget(self.btnPrevious, 2, 0, 1, 1)
        self.btnUpdate = QtWidgets.QPushButton(self.replayBtnGrid)
        self.btnUpdate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnUpdate.setObjectName("btnUpdate")
        self.gridLayout.addWidget(self.btnUpdate, 3, 0, 1, 1)
        self.btnReplay = QtWidgets.QPushButton(self.replayBtnGrid)
        self.btnReplay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnReplay.setObjectName("btnReplay")
        self.gridLayout.addWidget(self.btnReplay, 3, 1, 1, 1)
        self.titlePlaying = QtWidgets.QLabel(self.replayBtnGrid)
        self.titlePlaying.setObjectName("titlePlaying")
        self.gridLayout.addWidget(self.titlePlaying, 1, 0, 1, 1)
        self.lblFrameCount = QtWidgets.QLabel(self.replayBtnGrid)
        self.lblFrameCount.setText("")
        self.lblFrameCount.setObjectName("lblFrameCount")
        self.gridLayout.addWidget(self.lblFrameCount, 1, 1, 1, 2)
        self.btnStop = QtWidgets.QPushButton(self.replayBtnGrid)
        self.btnStop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnStop.setObjectName("btnStop")
        self.gridLayout.addWidget(self.btnStop, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.replayBtnGrid)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(REPLAY)
        QtCore.QMetaObject.connectSlotsByName(REPLAY)

    def retranslateUi(self, REPLAY):
        _translate = QtCore.QCoreApplication.translate
        self.titleFrames.setText(_translate("REPLAY", "FRAMES"))
        self.titleLoop.setText(_translate("REPLAY", "LOOP_REPLAY"))
        self.titleMode.setText(_translate("REPLAY", "MODE"))
        self.label.setText(_translate("REPLAY", "REPLAY_INFO"))
        self.deviceTitle.setText(_translate("REPLAY", "REPLAY_REQUIRED_BUS"))
        self.titleType.setText(_translate("REPLAY", "TYPE"))
        self.titleIface.setText(_translate("REPLAY", "INTERFACES"))
        self.titleBus.setText(_translate("REPLAY", "BUS"))
        self.btnSmartReplay.setText(_translate("REPLAY", "SMART_REPLAY"))
        self.btnSmartReplay.setProperty("cssClass", _translate("REPLAY", "btn-primary"))
        self.btnRevert.setText(_translate("REPLAY", "REVERT"))
        self.btnRevert.setProperty("cssClass", _translate("REPLAY", "btn-primary"))
        self.btnAddCommand.setText(_translate("REPLAY", "ADD_COMMAND"))
        self.btnSlice.setText(_translate("REPLAY", "SLICE"))
        self.btnSlice.setProperty("cssClass", _translate("REPLAY", "btn-primary"))
        self.btnCancel.setText(_translate("REPLAY", "CANCEL"))
        self.btnCancel.setProperty("cssClass", _translate("REPLAY", "btn-danger"))
        self.btnUpdateSession.setText(_translate("REPLAY", "UPDATE_SESSION"))
        self.btnUpdateSession.setProperty("cssClass", _translate("REPLAY", "btn-primary"))
        self.btnReplayAll.setText(_translate("REPLAY", "REPLAY_ALL"))
        self.btnReplayAll.setProperty("cssClass", _translate("REPLAY", "btn-primary"))
        self.btnNext.setText(_translate("REPLAY", "NEXT"))
        self.btnNext.setProperty("cssClass", _translate("REPLAY", "btn-primary"))
        self.btnPrevious.setText(_translate("REPLAY", "PREVIOUS"))
        self.btnPrevious.setProperty("cssClass", _translate("REPLAY", "btn-primary"))
        self.btnUpdate.setText(_translate("REPLAY", "UPDATE"))
        self.btnUpdate.setProperty("cssClass", _translate("REPLAY", "btn-primary"))
        self.btnReplay.setText(_translate("REPLAY", "REPLAY"))
        self.btnReplay.setProperty("cssClass", _translate("REPLAY", "btn-primary"))
        self.titlePlaying.setText(_translate("REPLAY", "PLAYING"))
        self.btnStop.setText(_translate("REPLAY", "STOP"))
        self.btnStop.setProperty("cssClass", _translate("REPLAY", "btn-danger"))

