# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form-sessions.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SESSIONS(object):
    def setupUi(self, SESSIONS):
        SESSIONS.setObjectName("SESSIONS")
        SESSIONS.resize(589, 488)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SESSIONS.sizePolicy().hasHeightForWidth())
        SESSIONS.setSizePolicy(sizePolicy)
        SESSIONS.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(SESSIONS)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sessionGridLoad = QtWidgets.QWidget(SESSIONS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sessionGridLoad.sizePolicy().hasHeightForWidth())
        self.sessionGridLoad.setSizePolicy(sizePolicy)
        self.sessionGridLoad.setObjectName("sessionGridLoad")
        self.formLayout_2 = QtWidgets.QFormLayout(self.sessionGridLoad)
        self.formLayout_2.setContentsMargins(0, -1, 0, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblRange = QtWidgets.QLabel(self.sessionGridLoad)
        self.lblRange.setObjectName("lblRange")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblRange)
        self.comboRange = QtWidgets.QComboBox(self.sessionGridLoad)
        self.comboRange.setObjectName("comboRange")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboRange)
        self.lblName = QtWidgets.QLabel(self.sessionGridLoad)
        self.lblName.setObjectName("lblName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblName)
        self.comboName = QtWidgets.QComboBox(self.sessionGridLoad)
        self.comboName.setObjectName("comboName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboName)
        self.lblAuthor = QtWidgets.QLabel(self.sessionGridLoad)
        self.lblAuthor.setObjectName("lblAuthor")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblAuthor)
        self.lblComment = QtWidgets.QLabel(self.sessionGridLoad)
        self.lblComment.setObjectName("lblComment")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblComment)
        self.fldAuthor = QtWidgets.QLineEdit(self.sessionGridLoad)
        self.fldAuthor.setReadOnly(True)
        self.fldAuthor.setObjectName("fldAuthor")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fldAuthor)
        self.fldComment = QtWidgets.QPlainTextEdit(self.sessionGridLoad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldComment.sizePolicy().hasHeightForWidth())
        self.fldComment.setSizePolicy(sizePolicy)
        self.fldComment.setMaximumSize(QtCore.QSize(16777215, 120))
        self.fldComment.setReadOnly(True)
        self.fldComment.setObjectName("fldComment")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fldComment)
        self.widgetBtn = QtWidgets.QWidget(self.sessionGridLoad)
        self.widgetBtn.setObjectName("widgetBtn")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetBtn)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnDelete = QtWidgets.QPushButton(self.widgetBtn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDelete.sizePolicy().hasHeightForWidth())
        self.btnDelete.setSizePolicy(sizePolicy)
        self.btnDelete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout.addWidget(self.btnDelete)
        self.btnShare = QtWidgets.QPushButton(self.widgetBtn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShare.sizePolicy().hasHeightForWidth())
        self.btnShare.setSizePolicy(sizePolicy)
        self.btnShare.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnShare.setObjectName("btnShare")
        self.horizontalLayout.addWidget(self.btnShare)
        self.btnLoad = QtWidgets.QPushButton(self.widgetBtn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoad.sizePolicy().hasHeightForWidth())
        self.btnLoad.setSizePolicy(sizePolicy)
        self.btnLoad.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLoad.setObjectName("btnLoad")
        self.horizontalLayout.addWidget(self.btnLoad)
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.widgetBtn)
        self.verticalLayout.addWidget(self.sessionGridLoad)
        self.sessionGridSave = QtWidgets.QWidget(SESSIONS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sessionGridSave.sizePolicy().hasHeightForWidth())
        self.sessionGridSave.setSizePolicy(sizePolicy)
        self.sessionGridSave.setObjectName("sessionGridSave")
        self.formLayout = QtWidgets.QFormLayout(self.sessionGridSave)
        self.formLayout.setContentsMargins(0, -1, 0, -1)
        self.formLayout.setObjectName("formLayout")
        self.lblSessionName = QtWidgets.QLabel(self.sessionGridSave)
        self.lblSessionName.setObjectName("lblSessionName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblSessionName)
        self.fldSessionName = QtWidgets.QLineEdit(self.sessionGridSave)
        self.fldSessionName.setObjectName("fldSessionName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fldSessionName)
        self.lblSessionComment = QtWidgets.QLabel(self.sessionGridSave)
        self.lblSessionComment.setObjectName("lblSessionComment")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblSessionComment)
        self.fldSessionComment = QtWidgets.QPlainTextEdit(self.sessionGridSave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldSessionComment.sizePolicy().hasHeightForWidth())
        self.fldSessionComment.setSizePolicy(sizePolicy)
        self.fldSessionComment.setMaximumSize(QtCore.QSize(16777215, 120))
        self.fldSessionComment.setObjectName("fldSessionComment")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fldSessionComment)
        self.verticalLayout.addWidget(self.sessionGridSave)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(SESSIONS)
        QtCore.QMetaObject.connectSlotsByName(SESSIONS)

    def retranslateUi(self, SESSIONS):
        _translate = QtCore.QCoreApplication.translate
        self.lblRange.setText(_translate("SESSIONS", "SESSION_LOAD_RANGE"))
        self.lblName.setText(_translate("SESSIONS", "SESSION_NAME"))
        self.lblAuthor.setText(_translate("SESSIONS", "SESSION_AUTHOR"))
        self.lblComment.setText(_translate("SESSIONS", "SESSION_COMMENT"))
        self.btnDelete.setText(_translate("SESSIONS", "DELETE"))
        self.btnDelete.setProperty("cssClass", _translate("SESSIONS", "btn-danger"))
        self.btnShare.setText(_translate("SESSIONS", "SHARE"))
        self.btnShare.setProperty("cssClass", _translate("SESSIONS", "btn-disabled"))
        self.btnLoad.setText(_translate("SESSIONS", "LOAD"))
        self.btnLoad.setProperty("cssClass", _translate("SESSIONS", "btn-success"))
        self.lblSessionName.setText(_translate("SESSIONS", "SESSION_NAME"))
        self.lblSessionComment.setText(_translate("SESSIONS", "SESSION_COMMENT"))

