# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form-signals.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SIGNAL(object):
    def setupUi(self, SIGNAL):
        SIGNAL.setObjectName("SIGNAL")
        SIGNAL.resize(828, 623)
        self.bodyLayout = QtWidgets.QHBoxLayout(SIGNAL)
        self.bodyLayout.setContentsMargins(0, 0, 0, 0)
        self.bodyLayout.setObjectName("bodyLayout")
        self.msgManager = QtWidgets.QWidget(SIGNAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgManager.sizePolicy().hasHeightForWidth())
        self.msgManager.setSizePolicy(sizePolicy)
        self.msgManager.setObjectName("msgManager")
        self.msgManagerLayout = QtWidgets.QVBoxLayout(self.msgManager)
        self.msgManagerLayout.setContentsMargins(-1, 0, -1, 0)
        self.msgManagerLayout.setObjectName("msgManagerLayout")
        self.widgetSelector = QtWidgets.QWidget(self.msgManager)
        self.widgetSelector.setObjectName("widgetSelector")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetSelector)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblSelector = QtWidgets.QLabel(self.widgetSelector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSelector.sizePolicy().hasHeightForWidth())
        self.lblSelector.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSelector.setFont(font)
        self.lblSelector.setObjectName("lblSelector")
        self.horizontalLayout.addWidget(self.lblSelector)
        self.comboSignalSelector = QtWidgets.QComboBox(self.widgetSelector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboSignalSelector.sizePolicy().hasHeightForWidth())
        self.comboSignalSelector.setSizePolicy(sizePolicy)
        self.comboSignalSelector.setObjectName("comboSignalSelector")
        self.horizontalLayout.addWidget(self.comboSignalSelector)
        self.msgManagerLayout.addWidget(self.widgetSelector)
        self.msgLine = QtWidgets.QFrame(self.msgManager)
        self.msgLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.msgLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.msgLine.setObjectName("msgLine")
        self.msgManagerLayout.addWidget(self.msgLine)
        self.bitsTable = QtWidgets.QTableView(self.msgManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bitsTable.sizePolicy().hasHeightForWidth())
        self.bitsTable.setSizePolicy(sizePolicy)
        self.bitsTable.setMinimumSize(QtCore.QSize(0, 450))
        self.bitsTable.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bitsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.bitsTable.setAlternatingRowColors(True)
        self.bitsTable.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.bitsTable.setCornerButtonEnabled(True)
        self.bitsTable.setObjectName("bitsTable")
        self.bitsTable.horizontalHeader().setMinimumSectionSize(15)
        self.msgManagerLayout.addWidget(self.bitsTable)
        spacerItem = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.msgManagerLayout.addItem(spacerItem)
        self.bodyLayout.addWidget(self.msgManager)
        self.editor = QtWidgets.QWidget(SIGNAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editor.sizePolicy().hasHeightForWidth())
        self.editor.setSizePolicy(sizePolicy)
        self.editor.setObjectName("editor")
        self.signalEditorLayout = QtWidgets.QVBoxLayout(self.editor)
        self.signalEditorLayout.setContentsMargins(0, 0, 0, 0)
        self.signalEditorLayout.setSpacing(0)
        self.signalEditorLayout.setObjectName("signalEditorLayout")
        self.cardMsg = QtWidgets.QWidget(self.editor)
        self.cardMsg.setProperty("cssClass", "")
        self.cardMsg.setObjectName("cardMsg")
        self.mainLayout = QtWidgets.QVBoxLayout(self.cardMsg)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.cardHeaderMsg = QtWidgets.QWidget(self.cardMsg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardHeaderMsg.sizePolicy().hasHeightForWidth())
        self.cardHeaderMsg.setSizePolicy(sizePolicy)
        self.cardHeaderMsg.setStyleSheet("")
        self.cardHeaderMsg.setObjectName("cardHeaderMsg")
        self.cardDisplayHLayout_2 = QtWidgets.QHBoxLayout(self.cardHeaderMsg)
        self.cardDisplayHLayout_2.setObjectName("cardDisplayHLayout_2")
        self.titleMsg = QtWidgets.QLabel(self.cardHeaderMsg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleMsg.sizePolicy().hasHeightForWidth())
        self.titleMsg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titleMsg.setFont(font)
        self.titleMsg.setStyleSheet("background:none;\n"
"border:0;\n"
"border-radius:0;")
        self.titleMsg.setObjectName("titleMsg")
        self.cardDisplayHLayout_2.addWidget(self.titleMsg)
        self.btnNewSignal = QtWidgets.QPushButton(self.cardHeaderMsg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewSignal.sizePolicy().hasHeightForWidth())
        self.btnNewSignal.setSizePolicy(sizePolicy)
        self.btnNewSignal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNewSignal.setObjectName("btnNewSignal")
        self.cardDisplayHLayout_2.addWidget(self.btnNewSignal)
        self.mainLayout.addWidget(self.cardHeaderMsg)
        self.cardSignalBody = QtWidgets.QWidget(self.cardMsg)
        self.cardSignalBody.setObjectName("cardSignalBody")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.cardSignalBody)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cardBodyMsg = QtWidgets.QWidget(self.cardSignalBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardBodyMsg.sizePolicy().hasHeightForWidth())
        self.cardBodyMsg.setSizePolicy(sizePolicy)
        self.cardBodyMsg.setStyleSheet("")
        self.cardBodyMsg.setProperty("cssClass", "")
        self.cardBodyMsg.setObjectName("cardBodyMsg")
        self.formDisplayLayout_2 = QtWidgets.QFormLayout(self.cardBodyMsg)
        self.formDisplayLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formDisplayLayout_2.setVerticalSpacing(6)
        self.formDisplayLayout_2.setObjectName("formDisplayLayout_2")
        self.labelName = QtWidgets.QLabel(self.cardBodyMsg)
        self.labelName.setObjectName("labelName")
        self.formDisplayLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelName)
        self.fldName = QtWidgets.QLineEdit(self.cardBodyMsg)
        self.fldName.setObjectName("fldName")
        self.formDisplayLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fldName)
        self.lblId = QtWidgets.QLabel(self.cardBodyMsg)
        self.lblId.setObjectName("lblId")
        self.formDisplayLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblId)
        self.fldId = QtWidgets.QLineEdit(self.cardBodyMsg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldId.sizePolicy().hasHeightForWidth())
        self.fldId.setSizePolicy(sizePolicy)
        self.fldId.setMaximumSize(QtCore.QSize(96, 16777215))
        self.fldId.setReadOnly(True)
        self.fldId.setObjectName("fldId")
        self.formDisplayLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fldId)
        self.labelECU = QtWidgets.QLabel(self.cardBodyMsg)
        self.labelECU.setObjectName("labelECU")
        self.formDisplayLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelECU)
        self.fldECU = QtWidgets.QLineEdit(self.cardBodyMsg)
        self.fldECU.setMaximumSize(QtCore.QSize(96, 16777215))
        self.fldECU.setObjectName("fldECU")
        self.formDisplayLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fldECU)
        self.verticalLayout.addWidget(self.cardBodyMsg)
        self.tabWidget = QtWidgets.QTabWidget(self.cardSignalBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabDetails = QtWidgets.QWidget()
        self.tabDetails.setObjectName("tabDetails")
        self.formLayout = QtWidgets.QFormLayout(self.tabDetails)
        self.formLayout.setContentsMargins(4, -1, 4, -1)
        self.formLayout.setObjectName("formLayout")
        self.labelStart = QtWidgets.QLabel(self.tabDetails)
        self.labelStart.setObjectName("labelStart")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelStart)
        self.fldStart = QtWidgets.QLineEdit(self.tabDetails)
        self.fldStart.setMaxLength(8)
        self.fldStart.setObjectName("fldStart")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fldStart)
        self.labelLen = QtWidgets.QLabel(self.tabDetails)
        self.labelLen.setObjectName("labelLen")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelLen)
        self.fldLen = QtWidgets.QLineEdit(self.tabDetails)
        self.fldLen.setMaxLength(3)
        self.fldLen.setObjectName("fldLen")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fldLen)
        self.checkSigned = QtWidgets.QCheckBox(self.tabDetails)
        self.checkSigned.setObjectName("checkSigned")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.checkSigned)
        self.comboEndian = QtWidgets.QComboBox(self.tabDetails)
        self.comboEndian.setObjectName("comboEndian")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboEndian)
        self.labelFactor = QtWidgets.QLabel(self.tabDetails)
        self.labelFactor.setObjectName("labelFactor")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelFactor)
        self.fldFactor = QtWidgets.QLineEdit(self.tabDetails)
        self.fldFactor.setMaxLength(8)
        self.fldFactor.setObjectName("fldFactor")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.fldFactor)
        self.labelOffset = QtWidgets.QLabel(self.tabDetails)
        self.labelOffset.setObjectName("labelOffset")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.labelOffset)
        self.fldOffset = QtWidgets.QLineEdit(self.tabDetails)
        self.fldOffset.setMaxLength(8)
        self.fldOffset.setObjectName("fldOffset")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.fldOffset)
        self.labelUnit = QtWidgets.QLabel(self.tabDetails)
        self.labelUnit.setObjectName("labelUnit")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.labelUnit)
        self.fldUnit = QtWidgets.QLineEdit(self.tabDetails)
        self.fldUnit.setMaxLength(16)
        self.fldUnit.setObjectName("fldUnit")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.fldUnit)
        self.labelComment = QtWidgets.QLabel(self.tabDetails)
        self.labelComment.setObjectName("labelComment")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.labelComment)
        self.labelMin = QtWidgets.QLabel(self.tabDetails)
        self.labelMin.setObjectName("labelMin")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.labelMin)
        self.labelMax = QtWidgets.QLabel(self.tabDetails)
        self.labelMax.setObjectName("labelMax")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.labelMax)
        self.fldMin = QtWidgets.QLineEdit(self.tabDetails)
        self.fldMin.setObjectName("fldMin")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.fldMin)
        self.fldMax = QtWidgets.QLineEdit(self.tabDetails)
        self.fldMax.setObjectName("fldMax")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.fldMax)
        self.fldComment = QtWidgets.QPlainTextEdit(self.tabDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fldComment.sizePolicy().hasHeightForWidth())
        self.fldComment.setSizePolicy(sizePolicy)
        self.fldComment.setMaximumSize(QtCore.QSize(160, 60))
        self.fldComment.setObjectName("fldComment")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.fldComment)
        self.tabWidget.addTab(self.tabDetails, "")
        self.tabValues = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabValues.sizePolicy().hasHeightForWidth())
        self.tabValues.setSizePolicy(sizePolicy)
        self.tabValues.setObjectName("tabValues")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabValues)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formValues = QtWidgets.QWidget(self.tabValues)
        self.formValues.setObjectName("formValues")
        self.gridValuesLayout = QtWidgets.QGridLayout(self.formValues)
        self.gridValuesLayout.setContentsMargins(4, 4, 4, 4)
        self.gridValuesLayout.setSpacing(4)
        self.gridValuesLayout.setObjectName("gridValuesLayout")
        self.btnAddValue = QtWidgets.QPushButton(self.formValues)
        self.btnAddValue.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAddValue.setObjectName("btnAddValue")
        self.gridValuesLayout.addWidget(self.btnAddValue, 0, 1, 1, 2)
        self.verticalLayout_2.addWidget(self.formValues)
        spacerItem1 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabValues, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.btnSave = QtWidgets.QPushButton(self.cardSignalBody)
        self.btnSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout.addWidget(self.btnSave)
        self.btnImport = QtWidgets.QPushButton(self.cardSignalBody)
        self.btnImport.setObjectName("btnImport")
        self.verticalLayout.addWidget(self.btnImport)
        self.btnDelete = QtWidgets.QPushButton(self.cardSignalBody)
        self.btnDelete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDelete.setObjectName("btnDelete")
        self.verticalLayout.addWidget(self.btnDelete)
        self.mainLayout.addWidget(self.cardSignalBody)
        self.signalEditorLayout.addWidget(self.cardMsg)
        self.bodyLayout.addWidget(self.editor)

        self.retranslateUi(SIGNAL)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SIGNAL)
        SIGNAL.setTabOrder(self.bitsTable, self.comboSignalSelector)
        SIGNAL.setTabOrder(self.comboSignalSelector, self.btnNewSignal)
        SIGNAL.setTabOrder(self.btnNewSignal, self.fldId)
        SIGNAL.setTabOrder(self.fldId, self.fldECU)
        SIGNAL.setTabOrder(self.fldECU, self.fldName)
        SIGNAL.setTabOrder(self.fldName, self.tabWidget)
        SIGNAL.setTabOrder(self.tabWidget, self.fldStart)
        SIGNAL.setTabOrder(self.fldStart, self.fldLen)
        SIGNAL.setTabOrder(self.fldLen, self.checkSigned)
        SIGNAL.setTabOrder(self.checkSigned, self.comboEndian)
        SIGNAL.setTabOrder(self.comboEndian, self.fldFactor)
        SIGNAL.setTabOrder(self.fldFactor, self.fldOffset)
        SIGNAL.setTabOrder(self.fldOffset, self.fldMin)
        SIGNAL.setTabOrder(self.fldMin, self.fldMax)
        SIGNAL.setTabOrder(self.fldMax, self.fldUnit)
        SIGNAL.setTabOrder(self.fldUnit, self.fldComment)
        SIGNAL.setTabOrder(self.fldComment, self.btnAddValue)
        SIGNAL.setTabOrder(self.btnAddValue, self.btnSave)
        SIGNAL.setTabOrder(self.btnSave, self.btnDelete)

    def retranslateUi(self, SIGNAL):
        _translate = QtCore.QCoreApplication.translate
        SIGNAL.setWindowTitle(_translate("SIGNAL", "Form"))
        self.lblSelector.setText(_translate("SIGNAL", "SIGNAL_SELECTOR"))
        self.editor.setProperty("cssClass", _translate("SIGNAL", "card"))
        self.cardHeaderMsg.setProperty("cssClass", _translate("SIGNAL", "cardHeader"))
        self.titleMsg.setText(_translate("SIGNAL", "SIGNAL_EDITOR"))
        self.titleMsg.setProperty("cssClass", _translate("SIGNAL", "cardTitle"))
        self.btnNewSignal.setText(_translate("SIGNAL", "NEW_SIGNAL"))
        self.btnNewSignal.setProperty("cssClass", _translate("SIGNAL", "btn-primary"))
        self.cardSignalBody.setProperty("cssClass", _translate("SIGNAL", "cardBody"))
        self.labelName.setText(_translate("SIGNAL", "NAME"))
        self.lblId.setText(_translate("SIGNAL", "ID"))
        self.labelECU.setText(_translate("SIGNAL", "ECU"))
        self.labelStart.setText(_translate("SIGNAL", "START"))
        self.labelLen.setText(_translate("SIGNAL", "LEN"))
        self.checkSigned.setText(_translate("SIGNAL", "SIGNED"))
        self.labelFactor.setText(_translate("SIGNAL", "FACTOR"))
        self.labelOffset.setText(_translate("SIGNAL", "OFFSET"))
        self.labelUnit.setText(_translate("SIGNAL", "UNIT"))
        self.labelComment.setText(_translate("SIGNAL", "COMMENT"))
        self.labelMin.setText(_translate("SIGNAL", "MIN"))
        self.labelMax.setText(_translate("SIGNAL", "MAX"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDetails), _translate("SIGNAL", "DETAILS"))
        self.btnAddValue.setText(_translate("SIGNAL", "ADD_VALUE"))
        self.btnAddValue.setProperty("cssClass", _translate("SIGNAL", "btn-primary"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabValues), _translate("SIGNAL", "VALUES"))
        self.btnSave.setText(_translate("SIGNAL", "SAVE"))
        self.btnSave.setProperty("cssClass", _translate("SIGNAL", "btn-disabled"))
        self.btnImport.setText(_translate("SIGNAL", "IMPORT"))
        self.btnImport.setProperty("cssClass", _translate("SIGNAL", "btn-primary"))
        self.btnDelete.setText(_translate("SIGNAL", "DELETE"))
        self.btnDelete.setProperty("cssClass", _translate("SIGNAL", "btn-disabled"))

