# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form-signals.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_body(object):
    def setupUi(self, body):
        body.setObjectName("body")
        body.resize(828, 532)
        self.bodyLayout = QtWidgets.QHBoxLayout(body)
        self.bodyLayout.setObjectName("bodyLayout")
        self.msgManager = QtWidgets.QWidget(body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgManager.sizePolicy().hasHeightForWidth())
        self.msgManager.setSizePolicy(sizePolicy)
        self.msgManager.setObjectName("msgManager")
        self.msgManagerLayout = QtWidgets.QVBoxLayout(self.msgManager)
        self.msgManagerLayout.setContentsMargins(-1, 0, -1, 0)
        self.msgManagerLayout.setObjectName("msgManagerLayout")
        self.msgGrid = QtWidgets.QWidget(self.msgManager)
        self.msgGrid.setStyleSheet("text-align:center;")
        self.msgGrid.setObjectName("msgGrid")
        self.gridLayout = QtWidgets.QGridLayout(self.msgGrid)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.b1 = QtWidgets.QLabel(self.msgGrid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b1.sizePolicy().hasHeightForWidth())
        self.b1.setSizePolicy(sizePolicy)
        self.b1.setMinimumSize(QtCore.QSize(24, 24))
        self.b1.setObjectName("b1")
        self.gridLayout.addWidget(self.b1, 0, 0, 1, 1)
        self.msgManagerLayout.addWidget(self.msgGrid)
        self.msgLine = QtWidgets.QFrame(self.msgManager)
        self.msgLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.msgLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.msgLine.setObjectName("msgLine")
        self.msgManagerLayout.addWidget(self.msgLine)
        self.widgetSelector = QtWidgets.QWidget(self.msgManager)
        self.widgetSelector.setObjectName("widgetSelector")
        self.selectorLayout = QtWidgets.QVBoxLayout(self.widgetSelector)
        self.selectorLayout.setObjectName("selectorLayout")
        self.labelSelector = QtWidgets.QLabel(self.widgetSelector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSelector.sizePolicy().hasHeightForWidth())
        self.labelSelector.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelSelector.setFont(font)
        self.labelSelector.setObjectName("labelSelector")
        self.selectorLayout.addWidget(self.labelSelector)
        self.signalSelector = QtWidgets.QComboBox(self.widgetSelector)
        self.signalSelector.setObjectName("signalSelector")
        self.selectorLayout.addWidget(self.signalSelector)
        self.msgManagerLayout.addWidget(self.widgetSelector)
        spacerItem = QtWidgets.QSpacerItem(1, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.msgManagerLayout.addItem(spacerItem)
        self.bodyLayout.addWidget(self.msgManager)
        self.editor = QtWidgets.QWidget(body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editor.sizePolicy().hasHeightForWidth())
        self.editor.setSizePolicy(sizePolicy)
        self.editor.setObjectName("editor")
        self.signalEditorLayout = QtWidgets.QVBoxLayout(self.editor)
        self.signalEditorLayout.setContentsMargins(0, 0, 0, 0)
        self.signalEditorLayout.setSpacing(0)
        self.signalEditorLayout.setObjectName("signalEditorLayout")
        self.cardMsg = QtWidgets.QWidget(self.editor)
        self.cardMsg.setObjectName("cardMsg")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cardMsg)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cardHeaderMsg = QtWidgets.QWidget(self.cardMsg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardHeaderMsg.sizePolicy().hasHeightForWidth())
        self.cardHeaderMsg.setSizePolicy(sizePolicy)
        self.cardHeaderMsg.setStyleSheet("")
        self.cardHeaderMsg.setObjectName("cardHeaderMsg")
        self.cardDisplayHLayout_2 = QtWidgets.QHBoxLayout(self.cardHeaderMsg)
        self.cardDisplayHLayout_2.setObjectName("cardDisplayHLayout_2")
        self.titleMsg = QtWidgets.QLabel(self.cardHeaderMsg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleMsg.sizePolicy().hasHeightForWidth())
        self.titleMsg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titleMsg.setFont(font)
        self.titleMsg.setStyleSheet("background:none;\n"
"border:0;\n"
"border-radius:0;")
        self.titleMsg.setObjectName("titleMsg")
        self.cardDisplayHLayout_2.addWidget(self.titleMsg)
        self.btnCollapseMsg = QtWidgets.QPushButton(self.cardHeaderMsg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCollapseMsg.sizePolicy().hasHeightForWidth())
        self.btnCollapseMsg.setSizePolicy(sizePolicy)
        self.btnCollapseMsg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCollapseMsg.setText("")
        self.btnCollapseMsg.setObjectName("btnCollapseMsg")
        self.cardDisplayHLayout_2.addWidget(self.btnCollapseMsg)
        self.verticalLayout_2.addWidget(self.cardHeaderMsg)
        self.cardBodyMsg = QtWidgets.QWidget(self.cardMsg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardBodyMsg.sizePolicy().hasHeightForWidth())
        self.cardBodyMsg.setSizePolicy(sizePolicy)
        self.cardBodyMsg.setStyleSheet("")
        self.cardBodyMsg.setObjectName("cardBodyMsg")
        self.formDisplayLayout_2 = QtWidgets.QFormLayout(self.cardBodyMsg)
        self.formDisplayLayout_2.setVerticalSpacing(6)
        self.formDisplayLayout_2.setObjectName("formDisplayLayout_2")
        self.labelName = QtWidgets.QLabel(self.cardBodyMsg)
        self.labelName.setObjectName("labelName")
        self.formDisplayLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelName)
        self.fldName = QtWidgets.QLineEdit(self.cardBodyMsg)
        self.fldName.setObjectName("fldName")
        self.formDisplayLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fldName)
        self.labelECU = QtWidgets.QLabel(self.cardBodyMsg)
        self.labelECU.setObjectName("labelECU")
        self.formDisplayLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelECU)
        self.fldECU = QtWidgets.QLineEdit(self.cardBodyMsg)
        self.fldECU.setObjectName("fldECU")
        self.formDisplayLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fldECU)
        self.verticalLayout_2.addWidget(self.cardBodyMsg)
        self.signalEditorLayout.addWidget(self.cardMsg)
        self.cardSignal = QtWidgets.QWidget(self.editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardSignal.sizePolicy().hasHeightForWidth())
        self.cardSignal.setSizePolicy(sizePolicy)
        self.cardSignal.setObjectName("cardSignal")
        self.cardSignalLayout = QtWidgets.QVBoxLayout(self.cardSignal)
        self.cardSignalLayout.setContentsMargins(-1, 9, -1, -1)
        self.cardSignalLayout.setSpacing(0)
        self.cardSignalLayout.setObjectName("cardSignalLayout")
        self.cardHeaderSignal = QtWidgets.QWidget(self.cardSignal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardHeaderSignal.sizePolicy().hasHeightForWidth())
        self.cardHeaderSignal.setSizePolicy(sizePolicy)
        self.cardHeaderSignal.setStyleSheet("")
        self.cardHeaderSignal.setObjectName("cardHeaderSignal")
        self.cardDisplayHLayout = QtWidgets.QHBoxLayout(self.cardHeaderSignal)
        self.cardDisplayHLayout.setObjectName("cardDisplayHLayout")
        self.titleSignal = QtWidgets.QLabel(self.cardHeaderSignal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleSignal.sizePolicy().hasHeightForWidth())
        self.titleSignal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titleSignal.setFont(font)
        self.titleSignal.setStyleSheet("background:none;\n"
"border:0;\n"
"border-radius:0;")
        self.titleSignal.setObjectName("titleSignal")
        self.cardDisplayHLayout.addWidget(self.titleSignal)
        self.btnCollapseSignal = QtWidgets.QPushButton(self.cardHeaderSignal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCollapseSignal.sizePolicy().hasHeightForWidth())
        self.btnCollapseSignal.setSizePolicy(sizePolicy)
        self.btnCollapseSignal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCollapseSignal.setText("")
        self.btnCollapseSignal.setObjectName("btnCollapseSignal")
        self.cardDisplayHLayout.addWidget(self.btnCollapseSignal)
        self.cardSignalLayout.addWidget(self.cardHeaderSignal)
        self.cardBodySignal = QtWidgets.QWidget(self.cardSignal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardBodySignal.sizePolicy().hasHeightForWidth())
        self.cardBodySignal.setSizePolicy(sizePolicy)
        self.cardBodySignal.setStyleSheet("")
        self.cardBodySignal.setObjectName("cardBodySignal")
        self.formDisplayLayout = QtWidgets.QFormLayout(self.cardBodySignal)
        self.formDisplayLayout.setVerticalSpacing(6)
        self.formDisplayLayout.setObjectName("formDisplayLayout")
        self.labelSignal = QtWidgets.QLabel(self.cardBodySignal)
        self.labelSignal.setObjectName("labelSignal")
        self.formDisplayLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelSignal)
        self.fldSignal = QtWidgets.QLineEdit(self.cardBodySignal)
        self.fldSignal.setObjectName("fldSignal")
        self.formDisplayLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fldSignal)
        self.labelStart = QtWidgets.QLabel(self.cardBodySignal)
        self.labelStart.setObjectName("labelStart")
        self.formDisplayLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelStart)
        self.fldStart = QtWidgets.QLineEdit(self.cardBodySignal)
        self.fldStart.setMaxLength(8)
        self.fldStart.setObjectName("fldStart")
        self.formDisplayLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fldStart)
        self.labelLen = QtWidgets.QLabel(self.cardBodySignal)
        self.labelLen.setObjectName("labelLen")
        self.formDisplayLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelLen)
        self.fldLen = QtWidgets.QLineEdit(self.cardBodySignal)
        self.fldLen.setMaxLength(3)
        self.fldLen.setObjectName("fldLen")
        self.formDisplayLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fldLen)
        self.checkSigned = QtWidgets.QCheckBox(self.cardBodySignal)
        self.checkSigned.setObjectName("checkSigned")
        self.formDisplayLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkSigned)
        self.fldEndian = QtWidgets.QComboBox(self.cardBodySignal)
        self.fldEndian.setObjectName("fldEndian")
        self.formDisplayLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fldEndian)
        self.labelFactor = QtWidgets.QLabel(self.cardBodySignal)
        self.labelFactor.setObjectName("labelFactor")
        self.formDisplayLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelFactor)
        self.fldFactor = QtWidgets.QLineEdit(self.cardBodySignal)
        self.fldFactor.setMaxLength(8)
        self.fldFactor.setObjectName("fldFactor")
        self.formDisplayLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fldFactor)
        self.labelOffset = QtWidgets.QLabel(self.cardBodySignal)
        self.labelOffset.setObjectName("labelOffset")
        self.formDisplayLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelOffset)
        self.fldOffset = QtWidgets.QLineEdit(self.cardBodySignal)
        self.fldOffset.setMaxLength(8)
        self.fldOffset.setObjectName("fldOffset")
        self.formDisplayLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fldOffset)
        self.labelUnit = QtWidgets.QLabel(self.cardBodySignal)
        self.labelUnit.setObjectName("labelUnit")
        self.formDisplayLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelUnit)
        self.fldUnit = QtWidgets.QLineEdit(self.cardBodySignal)
        self.fldUnit.setMaxLength(16)
        self.fldUnit.setObjectName("fldUnit")
        self.formDisplayLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.fldUnit)
        self.labelComment = QtWidgets.QLabel(self.cardBodySignal)
        self.labelComment.setObjectName("labelComment")
        self.formDisplayLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelComment)
        self.fldComment = QtWidgets.QLineEdit(self.cardBodySignal)
        self.fldComment.setObjectName("fldComment")
        self.formDisplayLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.fldComment)
        self.widget = QtWidgets.QWidget(self.cardBodySignal)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSave = QtWidgets.QPushButton(self.widget)
        self.btnSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnDelete = QtWidgets.QPushButton(self.widget)
        self.btnDelete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout.addWidget(self.btnDelete)
        self.formDisplayLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.widget)
        self.cardSignalLayout.addWidget(self.cardBodySignal)
        self.signalEditorLayout.addWidget(self.cardSignal)
        self.bodyLayout.addWidget(self.editor)

        self.retranslateUi(body)
        QtCore.QMetaObject.connectSlotsByName(body)

    def retranslateUi(self, body):
        _translate = QtCore.QCoreApplication.translate
        body.setWindowTitle(_translate("body", "Form"))
        self.b1.setText(_translate("body", "1"))
        self.labelSelector.setText(_translate("body", "SIGNAL_SELECTOR"))
        self.cardHeaderMsg.setProperty("cssClass", _translate("body", "cardHeader"))
        self.titleMsg.setText(_translate("body", "MSG"))
        self.titleMsg.setProperty("cssClass", _translate("body", "cardTitle"))
        self.cardBodyMsg.setProperty("cssClass", _translate("body", "cardBody"))
        self.labelName.setText(_translate("body", "NAME"))
        self.labelECU.setText(_translate("body", "ECU"))
        self.cardSignal.setProperty("cssClass", _translate("body", "card"))
        self.cardHeaderSignal.setProperty("cssClass", _translate("body", "cardHeader"))
        self.titleSignal.setText(_translate("body", "SIGNAL_EDITOR"))
        self.titleSignal.setProperty("cssClass", _translate("body", "cardTitle"))
        self.cardBodySignal.setProperty("cssClass", _translate("body", "cardBody"))
        self.labelSignal.setText(_translate("body", "SIGNAL"))
        self.labelStart.setText(_translate("body", "START"))
        self.labelLen.setText(_translate("body", "LEN"))
        self.checkSigned.setText(_translate("body", "SIGNED"))
        self.labelFactor.setText(_translate("body", "FACTOR"))
        self.labelOffset.setText(_translate("body", "OFFSET"))
        self.labelUnit.setText(_translate("body", "UNIT"))
        self.labelComment.setText(_translate("body", "COMMENT"))
        self.btnSave.setText(_translate("body", "SAVE"))
        self.btnDelete.setText(_translate("body", "DELETE"))

